"""Reviewable editorial decisions, appended per checkpoint."""
from enriquecer_v1 import *
def src(n,locator,url=None,tier='A'):
    candidates=[load(p) for p in sorted((ROOT/'03_FONTES/ENRIQUECIMENTO_V1').glob(f'{n:03}_*.json'))]
    meta=next((m for m in candidates if (not url or m['url']==url) and m['verificacao']=='PAGINA_CONSULTADA'),None)
    if meta:
        out={k:meta[k] for k in ['url','tier','accessed_on','verificacao','snapshot_sha256'] if k in meta}
        if n<=50 and '/api/appdetails' in meta['url']:
            out['retrieval_url']=meta['url'];out['url']=load(ROOT/'03_FONTES'/f'STEAM_{n:03}.json')['source_url']
    else:
        assert url, (n,'Missing consulted source')
        out=dict(url=url,tier=tier,accessed_on=now()[:10],verificacao='PAGINA_CONSULTADA')
    return dict(out,locator=locator)
def card(n,fact,locator,independence,typ='MECANICA_INTERATIVA',central='FORTE',**extra):
    source=extra.pop('source',None) or src(n,locator)
    return dict(fact=fact,type=typ,centrality=central,predicate='CONTROLAR' if typ=='MECANICA_INTERATIVA' else 'ANALISAR',source=source,independence=independence,**extra)
def dec(n,new=None,reason='',rejected=None,newsources=None):
    return dict(number=n,new=new or [],justificativa=reason or 'Fonte consultada oferece elemento distinto dos cards anteriores; ver justificativa de independência em cada acréscimo.',rejeitados=rejected or [],fontes_novas=newsources or [],fontes_consultadas=[str(p.relative_to(ROOT)).replace('\\','/') for p in sorted((ROOT/'03_FONTES/ENRIQUECIMENTO_V1').glob(f'{n:03}_*.json'))])
def batch1():
    return [
      dec(1,[card(1,'O jogador desenvolve o detetive combinando 24 habilidades e pensamentos no Thought Cabinet.','About this game — Countless tools for role playing','Sistema de desenvolvimento do personagem, distinto das ações investigativas e subornos de E01.')]),
      dec(25,[card(25,'O governante pode recrutar agentes para chantagear ou assassinar adversários.','About this game — Recruit agents','Rede de agentes e ações clandestinas; não repete transmissão dinástica de títulos de E01.'),card(25,'O jogador pode criar sua própria fé.','About this game — design your own faith','Criação religiosa é sistema distinto de sucessão e agentes.')]),
      dec(26,[card(26,'O jogador constrói pactos e alianças e pode usar ameaças militares e blefes para fazer adversários recuarem em conflitos.','About this game — diplomatic wiles / threats','Negociação externa coercitiva, distinta da administração econômica e institucional interna de E01.')]),
      dec(27,[card(27,'A capacidade do monarca influencia o ritmo de desenvolvimento nacional, e o jogador administra o gasto do poder do monarca.','About this game — Your nation’s pace of development','Recurso associado à capacidade pessoal do governante; não cria outro card para comércio, território ou religião já cobertos.')]),
      dec(28,reason='A apresentação oficial concentra-se na produção, alianças e planejamento militar já reunidos em E01. Projetar divisões e ordenar fábricas apenas detalharia esse núcleo; não há evento narrativo independente demonstrado.',rejected=[dict(elemento='Divisões militares e instruções fabris',motivo='Detalhamento do mesmo sistema de E01; não fatiar evidência.')]),
      dec(29,[card(29,'O jogador escolhe o líder separadamente da civilização; o líder permanece ao longo das eras e possui habilidade própria.','About this game — Play as visionary leaders of progress','Configuração independente de líder e civilização, distinta da expansão e tecnologia já descritas.')]),
      dec(30,[card(30,'Como presidente do comitê de campanha, o jogador recruta candidatos do partido, ajusta suas propostas e distribui recursos para favorecer sua eleição.','About this game — Control the Fate of Your Party','Gestão das candidaturas de terceiros, distinta da própria candidatura, legislação e orçamento de E01.')]),
      dec(31,[card(31,'O jogador pode buscar apoio de organizações e lobbies contratando um de seus representantes.','About this game — Organisations and Lobbies','Troca de apoio com organizações externas; E01 cobre eleição e votação legislativa.')]),
      dec(42,reason='A descrição oficial reúne abastecimento, calor e facções já cobertos em E01. Pesquisa e leis de calor são componentes do mesmo sistema. A campanha é apresentada genericamente, sem evento narrativo independente.',rejected=[dict(elemento='Leis e pesquisa sobre calor',motivo='Desdobramento do card de alocação de calor; independência insuficiente.')]),
      dec(44,[card(44,'Jack Boyd tem como objetivo juntar 500 mil dólares nos 180 dias que antecedem sua aposentadoria.','About this game — Your mission is clear','Meta narrativa individual de aposentadoria, distinta da rotina de gestão policial.','EVENTO_NARRATIVO','CENTRAL'),card(44,'O jogador pode enfrentar perguntas na sala de imprensa e, ocasionalmente, ser interrogado como testemunha.','About this game — press room / witness box','Situações de resposta pública e depoimento, diferentes de gerir agentes ou investigar crimes.','MECANICA_INTERATIVA','PONTUAL')])]
def batch2():
    abc='https://abc.com/news/6a71e133-eeef-4644-95f5-5b4797c54ec1/category/1088093'
    toc='https://press.uchicago.edu/Misc/Chicago/805328.html'
    nf=dict(url='https://www.netflix.com/title/80118100',tier='A',accessed_on='2026-09-26',verificacao='PAGINA_CONSULTADA',metodo='Página aberta via web; lista pública de episódios em inglês',locator='Season 2 — Episodes')
    return [
      dec(102,[card(102,'Na segunda temporada, Taylor Blaine acusa dois jogadores de basquete de drogá-lo, agredi-lo e publicar suas fotografias após uma festa escolar.','ABC Music Lounge — sinopse da segunda temporada','Outro caso e outra temporada; não repete o homicídio de E01.','EVENTO_NARRATIVO','CENTRAL',source=src(102,'Sinopse da segunda temporada',abc),unidade_documental={'temporada':2},escopo_centralidade='TEMPORADA')],newsources=[dict(url=abc,tier='A')]),
      dec(138,[card(138,'O episódio acompanha escândalos envolvendo Najib Razak, empréstimos duvidosos e endividamento da Malásia.','T2E2 The Man at the Top','Caso malaio independente dos casos empresariais e emissões descritos anteriormente.','ARGUMENTO_DOCUMENTAL','CENTRAL',source=dict(nf,locator='T2E2 The Man at the Top'),unidade_documental={'temporada':2,'episodio':2,'titulo_episodio':'The Man at the Top'},escopo_centralidade='EPISODIO'),card(138,'O episódio examina relações entre o fluxo de ouro para os Estados Unidos, lavagem de dinheiro, mineração ilegal e destruição ambiental.','T2E4 Dirty Gold','Cadeia do ouro constitui investigação distinta dos casos de crédito e veículos.','ARGUMENTO_DOCUMENTAL','CENTRAL',source=dict(nf,locator='T2E4 Dirty Gold'),unidade_documental={'temporada':2,'episodio':4,'titulo_episodio':'Dirty Gold'},escopo_centralidade='EPISODIO')],newsources=[dict(url=nf['url'],tier='A')]),
      dec(161,[card(161,'Bingham discute as pressões que a ameaça e a experiência do terrorismo internacional exercem sobre o Estado de Direito.','Descrição da editora — international terrorism','Discussão de uma pressão concreta, distinta da enumeração dos oito princípios.','ARGUMENTO_ACADEMICO','FORTE',source=src(161,'Descrição da editora — international terrorism',dossier(161)['fontes'][0]['url']))]),
      dec(164,[card(164,'Tocqueville descreve associações civis que fundam escolas e hospitais e sustenta que cidadãos de sociedades democráticas precisam cooperar voluntariamente para realizar empreendimentos comuns.','Volume II, Parte II, capítulo 5','Prática e argumento sobre associação civil, além da constatação geral de igualdade de condições.','ARGUMENTO_ACADEMICO','FORTE',source=src(164,'Volume II, Parte II, capítulo 5 — On the Use That the Americans Make of Association in Civil Life',toc),modo_discursivo='ARGUMENTAR')],newsources=[dict(url=toc,tier='A')]),
      dec(165,[card(165,'Arendt descreve a organização totalitária como uma estrutura deliberadamente instável, com instituições concorrentes e hierarquia variável, que impede previsibilidade e responsabilização.','Seção 3 — organização totalitária; OT pp. 364–369','Arranjo institucional descrito separadamente da propaganda e do apagamento entre fato e ficção de E01.','ARGUMENTO_ACADEMICO')]),
      dec(167,[card(167,'Os autores contrastam a pobreza da Coreia do Norte com a prosperidade da Coreia do Sul apesar da homogeneidade da população coreana, apresentando o contraste como exemplo do papel das instituições.','Descrição da editora — comparação entre as Coreias','Caso comparado identificável, distinto da formulação abstrata da tese de E01.','ARGUMENTO_ACADEMICO','FORTE',modo_discursivo='COMPARAR')]),
      dec(169,reason='A descrição da Yale já está representada por E01: fracasso de planos esquemáticos, conhecimento local e quatro casos. Transformar os casos apenas enumerados em novos cards repetiria a tese sem documentar um evento específico.',rejected=[dict(elemento='Cards separados para Tanzânia, Rússia, Brasília e China',motivo='A fonte enumera os casos, mas não fornece detalhes independentes suficientes para separar os fatos.')]),
      dec(179,[card(179,'Zuboff sustenta que direitos e leis devem submeter o poder do capitalismo de vigilância ao controle democrático.','Descrição da editora — demand the rights and laws','Posição normativa atribuída à autora, distinta do diagnóstico descritivo de captura do comportamento.','ARGUMENTO_ACADEMICO','FORTE',modo_discursivo='ARGUMENTAR')])]
def websrc(url,locator,tier='A'):
    return dict(url=url,locator=locator,tier=tier,accessed_on='2026-09-26',verificacao='PAGINA_CONSULTADA',metodo='Página aberta via ferramenta web; sem download local')
def batch3():
    la='https://support.rockstargames.com/articles/6GMrFpQcS19TdJ6ePxY9xt/what-to-do-if-you-are-stuck-on-an-l-a-noire-case'
    return [
      dec(2,reason='Steam e a ficha Nintendo já referenciada descrevem a coleção e a defesa em tribunal; não foi estabelecido um segundo evento independente. Não dividir a defesa dos clientes em cards genéricos de julgamento.'),
      dec(3,[card(3,'Ryunosuke Naruhodo procura desvendar uma conspiração criminosa internacional e um caso antigo ainda sem solução.','About this game — trama de Ryunosuke','Arco narrativo específico, distinto da sequência de coleta e apresentação de provas.','EVENTO_NARRATIVO','CENTRAL')]),
      dec(4,reason='Steam e consulta breve à loja oficial Capcom repetem a investigação de cenas de crime. Novidades de interface, galeria e reprodução automática não constituem novo fato documental pertinente.',newsources=[dict(url='https://us-store.captown.capcom.com/products/1080335-us',tier='A')]),
      dec(5,[card(5,'O jogador acompanha no diário os locais ainda com pistas ou pessoas para entrevistar e pode gastar pontos de intuição para revelar pistas no mapa.','Suporte oficial — What to do if you are stuck on a case','Procedimento interativo e recurso de auxílio, distintos da sinopse de Cole Phelps.','MECANICA_INTERATIVA','FORTE',source=websrc(la,'Resposta — diário Locations e pontos de Intuition'))],newsources=[dict(url=la,tier='A')]),
      dec(6,reason='A narrativa ramificada e as decisões sobre a vida dos androides já constam de E01. A sinopse não descreve uma mecânica independente; a afirmação de que escolhas mudam a história não basta.',rejected=[dict(elemento='Card mecânico de escolhas e finais',motivo='Repete a ramificação narrativa de E01 e a promessa genérica de design.')]),
      dec(7,[card(7,'O jogador pode invadir sistemas para obter informações ou usar habilidades sociais para extrair informações de personagens.','About this game — Choices and consequences','Alternativas interativas de acesso à informação, distintas da divisão social por aprimoramentos.')]),
      dec(8,[card(8,'O jogador seleciona e personaliza armas e aprimoramentos para adequá-los ao seu estilo de jogo.','About this game — HUMAN 2.0','Construção mecânica do personagem, distinta da segregação social da narrativa.')]),
      dec(10,[card(10,'No componente Red Dead Online incluído no produto, o jogador pode formar um grupo e comercializar bebida destilada clandestina.','About this game — Red Dead Online / form a posse; run moonshine','Atividade do componente online, não atribuída à campanha de Arthur Morgan.',unidade_documental={'componente':'Red Dead Online incluído em Red Dead Redemption 2'},escopo_centralidade='COMPONENTE_ONLINE')]),
      dec(11,reason='A descrição oficial e a busca breve na 2K só confirmam ascensão mafiosa e apresentação do remake. Não documentam um sistema específico de fiscalização de trânsito; não inferir essa mecânica.',rejected=[dict(elemento='Fiscalização de trânsito pela polícia',motivo='Busca breve não forneceu descrição concreta consultada da mecânica nesta edição.')]),
      dec(12,[card(12,'O jogador decide quais tenentes recompensar e quais trair na construção de seu império criminoso.','About this game — A new family on the ashes of the old','Escolha explícita de gestão de aliados, distinta do motivo narrativo de vingança.')])]
def batch4():
    mg='https://eu-support.konami.com/hc/en-gb/articles/9667449199255-Metal-Gear-Solid-V-Tactics'
    return [
      dec(13,reason='A página 2K consultada reafirma combate em esquadrão e tempestades; não identifica acontecimento narrativo independente. A busca breve não foi usada como prova de resgate ou atrocidade específica.'),
      dec(14,[card(14,'O jogador pode render inimigos apontando uma arma e agarrar e arrastar adversários caídos.','About this game — New gameplay actions','Ações interativas concretas, distintas do tema narrativo de transmissão de memórias.')]),
      dec(15,[card(15,'O jogador usa extração Fulton para retirar soldados que não resistem da área de operações e ampliar Diamond Dogs; dispositivos melhorados permitem extrair veículos e contêineres.','Suporte Konami — Fulton Extraction','Sistema de captura e transporte documentado, distinto da formação do exército na sinopse.',source=websrc(mg,'Fulton Extraction'))],newsources=[dict(url=mg,tier='A')]),
      dec(16,[card(16,'O administrador pode chantagear um inquilino por suas atividades ilegais para obter recursos para a própria família.','About this game — blackmail him','Extorsão para benefício familiar, distinta de transmitir denúncias ao Estado.')]),
      dec(17,reason='A descrição Steam e a busca breve mantêm o foco nas alternativas de carreira do funcionário. Não houve fonte aberta suficiente para documentar uma trama familiar separada.',rejected=[dict(elemento='Morte do pai como trama independente',motivo='Não sustentada pelas fontes concretas desta rodada.')]),
      dec(18,[card(18,'Um ataque terrorista na capital Bonton põe à prova o primeiro pesquisador humano do programa Orwell.','About this game — terror attack / Bonton','Evento desencadeador identificado, além do mecanismo geral de coleta e transmissão de dados.','EVENTO_NARRATIVO','CENTRAL')]),
      dec(19,[card(19,'Durante uma crise entre a Nação e Parges, o agente recebe a tarefa de investigar o editor Raban Vhart, sua esposa Karen e seu irmão Illya.','About this game — Reporting directly to Orwell adviser','Caso e personagens específicos, distintos da capacidade geral de manipular informação.','EVENTO_NARRATIVO','CENTRAL'),card(19,'O sistema de horário coloca o jogador em situações sensíveis ao tempo, nas quais importa quem investigar e quando.','About this game — time of day system','Restrição temporal de investigação, separada da fabricação de informação e da premissa diplomática.')]),
      dec(20,[card(20,'A narrativa familiar apresenta a escolha entre pagar o tratamento que pode salvar a avó e recorrer aos novos centros de transição do governo.','About this game — Craft the Narrative / Grandma','Dilema familiar específico, distinto da seleção e censura das notícias.','EVENTO_NARRATIVO','FORTE')]),
      dec(21,reason='A apresentação primária do criador só descreve a seleção de artigos favoráveis à nação, já registrada. Não inferir uma trama de reféns a partir de memória da obra.'),
      dec(22,[card(22,'Ao final do dia, o juiz confronta suas decisões com a família, cujos integrantes podem discordar delas.','About this game — At the end of a day / family','Confronto doméstico documentado, distinto da decisão judicial e da intriga entre facções.','EVENTO_NARRATIVO','FORTE')])]
def batch5():
    ob='https://www.nintendo.com/jp/topics/article/1c18e843-c55f-11e9-b641-063b7ac45a6d'
    return [
      dec(23,[card(23,'Um sistema de ressurreição permite conservar a experiência depois da morte e rever a estratégia para a continuação da jornada.','About this game — There and hereafter','Regra de persistência da experiência após a morte, diferente das trajetórias sociais da narrativa.')]),
      dec(24,reason='A apresentação detalha petições, recursos e alianças já presentes em E01. A referência genérica a problemas da família não identifica um evento independente; contratar auxiliares apenas detalha a gestão existente.'),
      dec(32,[card(32,'Depois do colapso das negociações do Brexit, um governo de extrema direita reúne e expulsa cidadãos de ascendência europeia; o protagonista é deslocado de sua vida anterior.','About this game — alternative Britain','Evento político de deslocamento, distinto da verificação cotidiana de documentos.','EVENTO_NARRATIVO','CENTRAL')]),
      dec(33,[card(33,'O jogador trabalha nas entradas de estabelecimentos, confere identificações e completa minijogos durante a viagem.','About this game — Work the doors / Check IDs','Rotina interativa documentada, distinta da prisão e da busca dos documentos de Eduardo.')]),
      dec(34,[card(34,'Rudy, pai solteiro, tenta sustentar a filha e manter sua loja quando um grande mercado abre ao lado.','About this game — Rudy','Situação narrativa de um personagem, distinta da operação editorial genérica.','EVENTO_NARRATIVO','FORTE')]),
      dec(35,[card(35,'Apesar da proibição do clube, o jogador pode intervir na vida das pessoas observadas, ajudando-as, extorquindo-as ou expondo-as.','About this game — Will you help / extort / expose','Intervenção ativa sobre os observados, distinta da observação passiva e da regra de não interferência de E01.')]),
      dec(36,reason='Steam e a página da Annapurna descrevem o mesmo banco de conversas e a mesma pesquisa por palavras. A origem NSA do banco apenas qualifica o objeto já documentado; o incidente que liga as quatro pessoas não é especificado.',rejected=[dict(elemento='Origem do banco de dados como card separado',motivo='Qualificador do mesmo conjunto de gravações; não constitui fato independente suficiente.')],newsources=[dict(url='https://annapurnainteractive.com/games/telling-lies',tier='A')]),
      dec(37,[card(37,'Em 1994, uma mulher britânica é entrevistada pela polícia sobre o desaparecimento do marido.','About this game — seven interviews from 1994','Ocorrência investigada e contexto narrativo; E01 descreve a consulta interativa aos vídeos.','EVENTO_NARRATIVO','CENTRAL')]),
      dec(38,[card(38,'O relógio Memento Mortem permite acessar os últimos instantes de pessoas mortas; o jogador deduz seus destinos e registra as conclusões no diário.','Nintendo — Memento Mortem e diário','Dispositivo de acesso ao passado, diferente da premissa de avaliação dos danos do navio.',source=websrc(ob,'Seção sobre 手記 e メメント・モーテム; apresentação oficial em japonês'))],newsources=[dict(url=ob,tier='A')]),
      dec(39,[card(39,'A narrativa acompanha uma família aristocrática amaldiçoada e a disputa por um ídolo misterioso.','About this game — cursed aristocratic family','Arco e objeto narrativos, distintos da resolução mecânica das doze mortes.','EVENTO_NARRATIVO','CENTRAL')])]
def batch6():
    kc='https://www.deepsilver.com/games/kingdom-come-deliverance-ii'; occ='https://occupation-game.whitepapergames.com/'
    return [
      dec(40,[card(40,'O jogador escolhe diferentes formações acadêmicas e origens sociais para Andreas.','About this game — Uncover mysteries','Configuração explícita do personagem, distinta da ocorrência dos homicídios.')]),
      dec(41,[card(41,'As habilidades de Henry evoluem pelo uso; armas, furtividade, forja e alquimia desenvolvem habilidades específicas e relacionadas.','Deep Silver — RPG Elements','Regra explícita de progressão por prática, além da promessa genérica de reação do mundo e da vingança de E01.',source=websrc(kc,'RPG Elements — Gameplay Decides your playstyle / Your actions are interrelated'))]),
      dec(43,[card(43,'O combate tático ocorre em tempo real com possibilidade de pausa e mecânicas baseadas no grupo de personagens.','About this game — Challenging, classic RPG combat','Sistema de combate, distinto da autoridade de aplicação das leis e das decisões políticas.')]),
      dec(45,reason='A descrição concreta é a revisão de oito casos já coberta em E01. O fragmento de notícia no início da página não identifica suficientemente um acontecimento próprio da narrativa; não tratá-lo como decisão judicial real nem criar conclusão jurídica.',rejected=[dict(elemento='Fragmento sobre flagrante e entrapment',motivo='Contexto documental insuficiente para atribuir um novo evento à obra com segurança.')]),
      dec(46,[card(46,'O jogador persegue e prende contrabandistas que tentam fugir da área de controle e pode comprar e melhorar viaturas.','About this game — Police chases','Perseguição veicular e captura, distintas da triagem documental e inspeção estática.'),card(46,'A situação na fronteira se agrava quando um colega do protagonista é morto durante uma intervenção.','About this game — comrade is killed','Evento narrativo específico; não repete a rotina interativa do posto.','EVENTO_NARRATIVO','FORTE')]),
      dec(47,[card(47,'O protagonista precisa conquistar a confiança da Estrutura para voltar a ver sua filha.','About this game — Gain the trust','Objetivo familiar condicionado à confiança institucional, distinto do diagnóstico e tratamento dos pacientes.','EVENTO_NARRATIVO','FORTE')]),
      dec(48,[card(48,'O jogador prepara coquetéis para alterar as emoções dos clientes e obter informações.','About this game — Psychological Bartending','Mecânica de atendimento e coleta de informação, distinta da trama corporativa.'),card(48,'O jogador assume a voz de figuras do projeto Social Psyche Welfare e usa conversas telefônicas para descobrir seus planos.','About this game — Vocal Corporate Espionage','Personificação vocal por telefone; sistema separado da preparação de bebidas.')]),
      dec(49,[card(49,'Uma explosão com muitas mortes precipita a adoção apressada de uma medida controversa que ameaça liberdades civis; o jornalista investiga os relatos da noite.','White Paper Games — apresentação de The Occupation','Evento desencadeador e resposta política, distintos das operações investigativas.','EVENTO_NARRATIVO','CENTRAL',source=websrc(occ,'Apresentação — explosion / controversial act'))],newsources=[dict(url=occ,tier='A')]),
      dec(50,[card(50,'O jogador fotografa o ambiente do jogo e compara suas imagens com fotografias de arquivo feitas por fotojornalistas.','About this game — PHOTOGRAPHY','Ação interativa de registro e comparação documental, distinta da premissa histórica de Reza.')])]
def batch7():
    dis='https://www.sundance.org/blogs/bryan-fogel-returns-to-the-festival-with-the-dissident-3/'
    return [
      dec(126,reason='As fontes descrevem o encontro e a comunicação preparatória de Snowden, já no mesmo núcleo de E01. A proteção da fonte e a vigilância sofrida pela diretora aparecem como bastidores; não convertidas automaticamente em acontecimentos mostrados no filme.'),
      dec(128,reason='A página oficial já liga o acampamento à mobilização posterior, como E01. A busca breve sobre a ocupação de 1977 não forneceu passagem aberta suficiente para um segundo evento do filme; não usar a campanha de impacto de 2020 como conteúdo do documentário.'),
      dec(129,[card(129,'O filme questiona a representação de pessoas negras em Hollywood.','PBS — About the Documentary','Argumento sobre representação cinematográfica, distinto da reconstrução das vidas e assassinatos dos três líderes.','ARGUMENTO_DOCUMENTAL')]),
      dec(130,reason='O episódio de Magdy contrariando ordens da Irmandade apenas concretiza a divisão de lealdades já registrada em E01. A entrevista também discute avaliação política posterior, que não será atribuída automaticamente ao filme.',rejected=[dict(elemento='Participação de Magdy no protesto de Mohamed Mahmoud',motivo='Mesmo conflito de lealdades já incluído no card existente.')]),
      dec(131,reason='Netflix confirma os 93 dias de protesto já registrados. A entrevista também trata de Freedom on Fire e A Rising Fury, obras distintas; não importar seus eventos de 2022 para Winter on Fire.',rejected=[dict(elemento='Eventos da invasão de 2022',motivo='Pertencem a outros filmes discutidos na entrevista.')]),
      dec(132,[card(132,'Segundo o diretor, a equipe de Navalny examinou mensagens e registros bancários de Christo Grozev para verificar se ele trabalhava para um serviço de inteligência estrangeiro.','Entrevista NPR — verificação de Grozev','Prática de verificação da credibilidade do colaborador, separada do telefonema sobre o envenenamento.','ARGUMENTO_DOCUMENTAL','PONTUAL')]),
      dec(133,[card(133,'O filme acompanha Hatice Cengiz defendendo um pedido de justiça perante as Nações Unidas.','Sundance — descrição do percurso de Hatice Cengiz','Ação pública posterior ao assassinato, distinta da reconstrução do homicídio.','EVENTO_HISTORICO','FORTE',source=websrc(dis,'Parágrafo The Dissident follows…',tier='B'))],newsources=[dict(url=dis,tier='B')]),
      dec(134,reason='A monetização da atenção explica o mesmo mecanismo de engajamento já coberto em E01. A fonte não especifica outra prática independente; não duplicar o argumento com vocabulário publicitário.',rejected=[dict(elemento='Venda de atenção a anunciantes',motivo='Mecanismo econômico do mesmo fato de engajamento já documentado.')]),
      dec(135,[card(135,'O documentário descreve manipulação de operações com títulos, distorção de balanços e engano a investidores por integrantes da direção da Enron.','PBS — About the Documentary / manipulate securities trading','Práticas contábeis e informacionais, distintas do resultado do colapso e das perdas de E01.','ARGUMENTO_DOCUMENTAL','FORTE')],reason='Mantidas apenas práticas descritas no filme; condenações de 2006 mencionadas na ficha de exibição de 2007 não foram automaticamente atribuídas à edição cinematográfica de 2005.'),
      dec(136,reason='Cannes e o presskit oficial reiteram crise, desregulamentação e corrupção das relações financeiras. Sem um caso independente suficientemente detalhado nesta consulta; não separar consequências gerais da própria crise em cards artificiais.',newsources=[dict(url='https://www.sonyclassics.com/insidejob/_pdf/insidejob_presskit.pdf',tier='A')])]
def batch8():
    cleaner='https://www.beetz-brothers.com/wp-content/uploads/2017/06/PressKit-THE-CLEANERS-PDF.pdf'
    return [
      dec(137,[card(137,'Alex Winter apresenta o filme como uma investigação de como a organização da economia facilita a desigualdade de renda.','ICIJ — declaração do diretor sobre overarching significance','Tese documental explicitamente atribuída ao diretor, distinta do método de colaboração jornalística de E01.','ARGUMENTO_DOCUMENTAL','FORTE',modo_discursivo='ARGUMENTAR')]),
      dec(139,[card(139,'Segundo a produtora, o filme expôs o consumo de carne de golfinho contaminada com mercúrio por crianças em escolas japonesas.','OPS — indicador de impacto sobre school children / mercury-laced dolphin meat','Destino alimentar e exposição ao mercúrio, distintos da missão de filmar a caça.','ARGUMENTO_DOCUMENTAL','FORTE')]),
      dec(141,[card(141,'Os realizadores relatam que moderadores participantes do filme apresentam sofrimento traumático ligado às imagens que precisam examinar diariamente, com restrições para falar do trabalho até com suas famílias.','Presskit — Directors’ Notes, página impressa 07','Condições e consequências do trabalho para os moderadores, distintas da escolha de remover conteúdo.','ARGUMENTO_DOCUMENTAL','FORTE',source=websrc(cleaner,'Directors’ Notes — página 07'))],newsources=[dict(url=cleaner,tier='A')]),
      dec(144,reason='O Media Center contém apenas a sinopse já incorporada. A busca breve sobre sindicalização não acrescentou passagem aberta suficiente; não inferir uma votação específica apenas pelo choque entre empresa e trabalhadores.'),
      dec(145,reason='A ficha IDA e a busca institucional breve reiteram a luta pela libertação e a criação dos filhos. Duração da pena e anos de campanha qualificam esse mesmo núcleo, sem novo fato independente.'),
      dec(146,reason='PBS e IDFA descrevem a mesma resistência à barreira, acompanhada ao longo do crescimento do filho. Arrancamento de oliveiras e protestos são componentes da construção já documentada; não fatiar essa sequência.'),
      dec(147,[card(147,'Sem serviços médicos disponíveis, Hamza e seus amigos organizam um hospital em Aleppo.','PBS Frontline — transcrição: Without the regime / set up a hospital','Organização de atendimento médico, distinta da trajetória conjugal e da carta à filha.','EVENTO_HISTORICO','FORTE')]),
      dec(148,reason='A ficha DFI descreve o segredo sobre a fuga e a vida adulta já incluídos no card. As notícias associadas tratam de prêmios e produção, sem outro acontecimento demonstrado na fonte principal.'),
      dec(149,reason='Acesso direto ao SFFILM recebeu HTTP 403, mas a página foi aberta via web; o site oficial também foi consultado. Ambos reafirmam censura e resistência jornalística. A busca de referendo não sustentou novo evento independente.',newsources=[dict(url='https://www.badpress.film/',tier='A')]),
      dec(151,reason='A descrição PBS repete a coalizão e a ratificação na Virgínia já cobertas. Créditos de arquivo e biografias não demonstram fatos adicionais da obra.')]
def batch9():
    dog='https://releasing.dogwoof.com/black-box-diaries'
    sic=dossier(159)['fontes'][0]['url']
    return [
      dec(152,reason='A sinopse HRW descreve a mesma mobilização e sua repressão em termos gerais. Identidade da realizadora e advertências de conteúdo não sustentam novo evento independente.'),
      dec(154,reason='IDA, Variety e a distribuidora Dogwoof reafirmam investigação e luta institucional já cobertas. O processo civil é desdobramento desse núcleo; a biografia da autora e ações de impacto posteriores não serão atribuídas ao filme.',newsources=[dict(url=dog,tier='A')]),
      dec(155,reason='A sinopse CPFL repete o sequestro e a trajetória do sequestrador já reunidos no card; imagens de arquivo são método de realização, sem outro fato sustentado.'),
      dec(156,reason='LISA/USP identifica entrevistados e lados do conflito já coberto. Não separar policiais, traficantes e moradores em três cards do mesmo objeto.'),
      dec(157,reason='A fonte Unibanco descreve as audiências e a internação já cobertas. A consulta breve não documentou outra prática independente; não inferir fatos da produção ou generalizar juízo sobre ressocialização.'),
      dec(159,[card(159,'Debates sobre feminismo, questões LGBT e antirracismo nas ocupações transformam as relações e a maneira como os jovens protagonistas se reconhecem e se apresentam.','SICAV — transformações pessoais dos protagonistas','Dimensão de formação pessoal e relações dentro do movimento, distinta da ocupação contra a reorganização escolar.','ARGUMENTO_DOCUMENTAL','FORTE',source=websrc(sic,'Parágrafos sobre conquistas individuais e explicação da diretora',tier='B'))],reason='HTTP 406 no acesso direto; conteúdo integral consultado via ferramenta web.'),
      dec(160,reason='A produtora fornece somente a acusação de financiamento da repressão já documentada. Não inferir participação direta em tortura sem fonte independente.')]

def batch10():
    return [
      dec(166,reason='Descrição da editora reafirma erosão institucional e enumera exemplos já no card. Não há outra proposição concreta independente nesta fonte.'),
      dec(168,reason='Os exemplos históricos apenas ilustram o equilíbrio Estado/sociedade de E01; a ficha não detalha um caso autônomo. Não criar card de cada país listado.'),
      dec(170,[card(170,'Lewis relata que a administração de saída preparou livros de transição durante nove meses, mas a equipe de Trump não compareceu para receber os esclarecimentos previstos.','PBS — transcrição, What is supposed to happen','Omissão na transferência institucional de conhecimento, distinta de substituir servidores por aliados.','PRATICA_INSTITUCIONAL','FORTE',source=src(170,'Transcrição — preparação e ausência nas reuniões de transição',url=dossier(170)['fontes'][0]['url'],tier='B'))]),
      dec(171,[card(171,'Alexander defende que o fim do encarceramento em massa de pessoas negras exige um amplo movimento social.','PBS/WNET — último período da apresentação da tese','Proposição de ação coletiva, distinta do diagnóstico de controle racial.','ARGUMENTO_ACADEMICO','FORTE',source=src(171,'Apresentação — major social movement',url=dossier(171)['fontes'][0]['url'],tier='B'),modo_discursivo='ARGUMENTAR')]),
      dec(172,[card(172,'Desmond argumenta que o despejo é também causa da pobreza, e não somente uma consequência de baixos recursos.','Editora — depoimento do autor sobre Arleen / eviction is a cause','Tese causal explicitada pelo autor, distinta da apresentação das oito famílias estudadas.','ARGUMENTO_ACADEMICO','FORTE',modo_discursivo='ARGUMENTAR')]),
      dec(173,reason='Salários, aluguel, crédito e subsídios são mecanismos da tese de manutenção da pobreza já registrada. A proposta genérica de abolição da pobreza não foi desdobrada em outro card sem medida independente concreta.'),
      dec(174,reason='Datas e destinos dos três protagonistas apenas detalham as trajetórias já reunidas em E01. Não dividir a Grande Migração em cards com a mesma função documental.'),
      dec(175,reason='A descrição da editora repete pilares e comparação entre castas. Nomes de exemplos e menção promocional a decisão judicial posterior não são novos argumentos da obra.'),
      dec(176,[card(176,'McGhee denomina dividendo da solidariedade os benefícios obtidos quando pessoas de diferentes grupos raciais se organizam para alcançar resultados que isoladamente não conseguiriam.','Editora — Solidarity Dividend','Tese sobre benefícios da cooperação, distinta do diagnóstico de custos do racismo.','ARGUMENTO_ACADEMICO','FORTE',modo_discursivo='ARGUMENTAR')]),
      dec(177,reason='A descrição oficial repete opacidade, falta de contestação e discriminação algorítmica já cobertas. Elogios e biografia da autora não fundamentam outro fato da obra.')]

def batch11():
    return [
      dec(180,reason='A notícia PBS descreve ação contra a publicação, não acontecimento narrado nas memórias. Não incorporada como conteúdo do livro; editora retornou HTTP 403.',rejected=[dict(elemento='Ação governamental sobre receitas do livro',motivo='Evento externo à narrativa publicada; a fonte não demonstra presença no livro.')]),
      dec(181,[card(181,'Holmes e Sunny Balwani procuraram silenciar funcionários e jornalistas que manifestavam dúvidas sobre a Theranos.','Editora — worked to silence anyone','Prática de controle de informações e reação a críticos, distinta da existência da fraude corporativa.','EVENTO_HISTORICO','FORTE')]),
      dec(182,[card(182,'Segundo a descrição do livro, a promoção do OxyContin envolveu cooptação de médicos, influência sobre a FDA e minimização de seu potencial de dependência.','Editora — marketed with a ruthless technique','Práticas de promoção e relacionamento institucional, distintas da trajetória patrimonial e reputacional da família.','PRATICA_INSTITUCIONAL','FORTE')]),
      dec(183,[card(183,'Mais de vinte anos depois da morte de Henrietta, pesquisadores passaram a estudar seu marido e seus filhos sem consentimento informado; foi nesse contexto que a família soube da continuidade das células.','Editora — família e pesquisa posterior','Novo episódio com outros participantes e outra coleta, distinto da retirada inicial de células em 1951.','EVENTO_HISTORICO','FORTE',source=src(183,'Descrição — more than twenty years / husband and children',url=dossier(183)['fontes'][1]['url']))]),
      dec(184,reason='O site da autora repete a análise das marcas já incluída. A página de The Shock Doctrine documenta outro livro; não transferir seus argumentos para No Logo.'),
      dec(185,reason='Violência, privatização e exploração da desorientação são o mesmo mecanismo de E01. Casos geográficos apenas enumerados não sustentam novas unidades independentes.'),
      dec(187,reason='Site oficial confirma autoria e tese; Harvard permanece bloqueado. Biografias e trabalhos posteriores dos autores não demonstram novo argumento do livro.'),
      dec(189,reason='A descrição Penguin repete a greve. O temperamento de Étienne é caracterização, sem evento independente que justifique outro card.'),
      dec(190,reason='A descrição repete Valjean, Javert e a proteção da filha de Fantine já reunidos. Não extrair acontecimentos da biografia de Hugo nem da produção do audiolivro.'),
      dec(192,reason='A fonte repete o testemunho prisional já registrado. Histórico de edições, adaptação cinematográfica e comentário biográfico não são novos acontecimentos das memórias.')]

def batch12():
    vida='https://graciliano.com.br/2012/09/temposfuturos-vidas-secas-de-graciliano-ramos/'
    return [
      dec(193,[card(193,'Arbex relata internações no Colônia sem critérios médicos, incluindo pessoas rejeitadas por sua condição social ou sexualidade.','IHU — resposta O que foi o Colônia?','Prática de admissão e segregação anterior às condições de permanência e mortes de E01.','PRATICA_INSTITUCIONAL','FORTE'),card(193,'Segundo Arbex, entre 1969 e 1980, o Colônia vendeu 1.853 corpos a 17 faculdades de medicina sem autorização das famílias.','IHU — resposta sobre venda de corpos','Comercialização após a morte, distinta das internações e dos maus-tratos.','EVENTO_HISTORICO','FORTE')]),
      dec(194,reason='A prevenção da AIDS especifica o atendimento voluntário já registrado; os nomes de internos não vêm acompanhados de acontecimentos independentes.'),
      dec(195,reason='A editora repete a rede e os métodos de extermínio de E01. A biografia do jornalista não comprova novo caso da obra.'),
      dec(196,[card(196,'Na reconstrução histórica apresentada por Almeida, discursos pseudocientíficos associaram diferenças biológicas e ambientais a atributos morais e intelectuais e sustentaram a continuidade da exploração colonial após a abolição.','SciELO — discussão do primeiro capítulo, raça e teorias biológicas','Argumento histórico sobre a legitimação pseudocientífica, distinto da definição estrutural geral.','ARGUMENTO_ACADEMICO','FORTE',modo_discursivo='HISTORIAR')]),
      dec(197,[card(197,'Davis aborda o sistema de cessão de pessoas negras encarceradas para o trabalho como ligação entre escravidão e controle social pelo encarceramento.','Boitempo — Neste livro, tal discussão / contratação de pessoas encarceradas','Prática histórica concreta, além da formulação geral das interseções de opressões.','PRATICA_INSTITUCIONAL','FORTE',source=websrc(dossier(197)['fontes'][0]['url'],'Descrição extensa — contratação de pessoas encarceradas'))],reason='Resposta HTTP direta não decodificável; texto efetivamente lido na página aberta pela ferramenta web. Não incorporadas referências da ficha a entrevistas posteriores.'),
      dec(198,reason='Diversidade, resistência e recusa da superioridade humana desenvolvem a mesma crítica da separação natureza/humanidade. O discurso de 1987 aparece como biografia; não atribuído às conferências sem prova.'),
      dec(200,[card(200,'Fabiano decide sacrificar Baleia por suspeitar que a cadela esteja doente; atira nela enquanto Sinhá Vitória tenta conter o sofrimento dos filhos.','Ensaio Tempos futuros — discussão de Baleia e passagens do romance','Evento familiar específico, distinto da retirada provocada pela seca.','EVENTO_NARRATIVO','FORTE',source=dict(url=vida,tier='B',locator='Análise de Baleia, com passagens das páginas 103–105 da edição citada no ensaio',accessed_on='2026-09-26',verificacao='PAGINA_CONSULTADA',snapshot_sha256='a34af5498fe6c0bb27f14c28103dcd09e7981dc48ecd234eb21d17587444e326',metodo='Ensaio com citações primárias consultado por HTTP; falha prévia da ferramenta web'))],newsources=[dict(url=vida,tier='B')])]

if __name__=='__main__': checkpoint(globals()['batch'+sys.argv[1]]())
