#pragma once
// CANDIDATO (nao substitui o header do baseline): + overlay CF88_WORK_REFERENCE_ADDITIONS.json sha256 e6cb6b04994c2e224fb1bd838b840c481755a3b305f6355da36e038258f5dcae
// GERADO por DEVICE_INTEGRATION/tools/build_ref_detail_header.py - NAO EDITAR.
// Metadados editoriais APROVADOS (RC2 revisado) dos vinculos obra <-> dispositivo, transportados sem reescrita.
// Fonte: LEGAL_TARGET_ID/derived/CF88_REFERENCES_CANONICAL.json sha256 89bd39c48c45e71eeb4b14c4e323f67c2e945c14ded8c86089c37e6578e19319
// Filtro: linhas WORK_REFERENCE CURRENT_VISIBLE do REF_PAYLOAD aprovado sha256 24b4f0d97ec004303a6e327a6abf76054eeb05c8cd2a44a424bd70c8341f58ea
// Vinculos: 122 de 122 visiveis. REFERENCE_DETAIL_INCOMPLETE (campos ausentes): tipo=0, ano=0, nota=18, sobre=0, por_que=0, temas=122
// nota = score_editorial do VINCULO x 10 (-1 = ausente). Ordenado por chave "TARGET_ID|WORK_ID" (bytewise).
#define LEXV1_REF_DETAIL_SCHEMA 1
#define LEXV1_REF_DETAIL_COUNT 122
#define LEXV1_REF_DETAIL_SOURCE_SHA256 "89bd39c48c45e71eeb4b14c4e323f67c2e945c14ded8c86089c37e6578e19319"
struct LexV1RefDetalhe { const char *chave, *titulo, *tipo; uint16_t ano; int16_t nota10;
                        const char *sobre, *porQue, *alcance, *relacao, *fonte; };
static const LexV1RefDetalhe LEXV1_REF_DETALHES[LEXV1_REF_DETAIL_COUNT] = {
  {"ADCT:ART.68|EXP-LIV-005", "Torto Arado", "LIVRO", 2019, 92,
   "Romance sobre irm\xc3\xa3s de comunidade rural negra, trabalho, terra, ancestralidade e resist\xc3\xaancia.",
   "O romance narra a vida de descendentes de escravizados que trabalham em uma fazenda na Bahia e lutam pela terra onde vivem.",
   "Ajuda a compreender o sentido de reconhecer a terra das comunidades quilombolas. \xc3\x89 fic\xc3\xa7\xc3\xa3o; n\xc3\xa3o descreve o procedimento de titula\xc3\xa7\xc3\xa3o.", "", "EXP-LIV-005 \xc2\xb7 REFERENCE_EXPANSION_01"},
  {"CF88:ART.134:CAPUT|EXP2-FIL-006", "Luta por Justi\xc3\xa7""a", "FILME", 2019, 78,
   "O jovem advogado Bryan Stevenson enfrenta uma batalha judicial por justi\xc3\xa7""a, em dramatiza\xc3\xa7\xc3\xa3o de sua atua\xc3\xa7\xc3\xa3o profissional.",
   "O filme acompanha Bryan Stevenson defendendo gratuitamente condenados pobres, incluindo um homem inocente no corredor da morte.",
   "Ajuda a compreender por que a defesa t\xc3\xa9""cnica dos necessitados \xc3\xa9 fun\xc3\xa7\xc3\xa3o essencial \xc3\xa0 Justi\xc3\xa7""a. A organiza\xc3\xa7\xc3\xa3o \xc3\xa9 privada e o sistema \xc3\xa9 norte-americano; n\xc3\xa3o demonstra a estrutura da Defensoria brasileira.\x0aLimites: Organiza\xc3\xa7\xc3\xa3o privada norte-americana, n\xc3\xa3o Defensoria P\xc3\xba""blica.", "", "EXP2-FIL-006 \xc2\xb7 REFERENCE_EXPANSION_01"},
  {"CF88:ART.144:PAR.5|EXP2-FIL-038", "Tropa de Elite", "FILME", 2007, 74,
   "O filme acompanha o dia a dia de um grupo de policiais do BOPE e de um capit\xc3\xa3o que quer deixar a corpora\xc3\xa7\xc3\xa3o e tenta encontrar um substituto para seu posto.",
   "O filme acompanha o batalh\xc3\xa3o de opera\xc3\xa7\xc3\xb5""es especiais da Pol\xc3\xad""cia Militar do Rio de Janeiro.",
   "Ajuda a visualizar o papel da pol\xc3\xad""cia militar e a problematizar os limites constitucionais da atua\xc3\xa7\xc3\xa3o policial. N\xc3\xa3o ensina a reparti\xc3\xa7\xc3\xa3o de compet\xc3\xaancias das demais pol\xc3\xad""cias.\x0aLimites: Retrata tortura e viol\xc3\xaancia policial sem endoss\xc3\xa1-las juridicamente; a ficha deve deixar isso claro.", "", "EXP2-FIL-038 \xc2\xb7 REFERENCE_EXPANSION_01"},
  {"CF88:ART.144:PAR.7|EXP-SER-002", "A Escuta", "S\xc3\x89RIE", 2002, 72,
   "Retrato sist\xc3\xaamico de pol\xc3\xad""cia, porto, pol\xc3\xadtica municipal, escolas e imprensa em Baltimore.",
   "A s\xc3\xa9rie mostra como metas, estat\xc3\xadsticas e disputas internas distorcem o trabalho policial em Baltimore.",
   "Ajuda a problematizar o que significa efici\xc3\xaancia na seguran\xc3\xa7""a p\xc3\xba""blica. Sistema estrangeiro; n\xc3\xa3o descreve a lei brasileira que organiza o setor.\x0aLimites: Contexto norte-americano.", "", "EXP-SER-002 \xc2\xb7 REFERENCE_EXPANSION_01"},
  {"CF88:ART.145:PAR.1|EXP-LIV-009", "O Triunfo da Injusti\xc3\xa7""a", "LIVRO", 2019, 82,
   "Investiga\xc3\xa7\xc3\xa3o econ\xc3\xb4mica sobre regressividade tribut\xc3\xa1ria, evas\xc3\xa3o dos ricos e propostas de reforma.",
   "Saez e Zucman mostram que, nos Estados Unidos, os mais ricos chegaram a pagar al\xc3\xadquota efetiva menor que a da m\xc3\xa9""dia da popula\xc3\xa7\xc3\xa3o.",
   "Ajuda a compreender e problematizar a capacidade contributiva e a progressividade. Dados norte-americanos; n\xc3\xa3o descreve os tributos brasileiros.\x0aLimites: Dados dos EUA.", "", "EXP-LIV-009 \xc2\xb7 REFERENCE_EXPANSION_01"},
  {"CF88:ART.14:CAPUT|REF-FIL-0005", "Selma", "FILME", 2014, 74,
   "A narrativa acompanha a mobiliza\xc3\xa7\xc3\xa3o de King e a marcha de Selma a Montgomery pelo movimento de direitos civis.",
   "A narrativa acompanha a mobiliza\xc3\xa7\xc3\xa3o de King e a marcha de Selma a Montgomery pelo movimento de direitos civis. A refer\xc3\xaancia ajuda a compreender o direito ao voto como forma de participa\xc3\xa7\xc3\xa3o popular. N\xc3\xa3o demonstra as modalidades e os requisitos eleitorais brasileiros.",
   "o direito ao voto como forma de participa\xc3\xa7\xc3\xa3o popular", "Contextualiza\xc3\xa7\xc3\xa3o hist\xc3\xb3rica", "REF-FIL-0005"},
  {"CF88:ART.170:CAPUT|EXP-DOC-002", "Capital no S\xc3\xa9""culo XXI", "DOCUMENT\xc3\x81RIO", 2019, -1,
   "Baseado em Piketty, o document\xc3\xa1rio investiga a distribui\xc3\xa7\xc3\xa3o de riqueza e seus rendimentos.",
   "Baseado em Piketty, o document\xc3\xa1rio investiga a distribui\xc3\xa7\xc3\xa3o de riqueza e seus rendimentos. A refer\xc3\xaancia ajuda a compreender a justi\xc3\xa7""a social e a exist\xc3\xaancia digna como finalidades da ordem econ\xc3\xb4mica. N\xc3\xa3o representa a organiza\xc3\xa7\xc3\xa3o integral da economia nem os instrumentos econ\xc3\xb4micos previstos nos incisos.",
   "a justi\xc3\xa7""a social e a exist\xc3\xaancia digna como finalidades da ordem econ\xc3\xb4mica", "Contextualiza\xc3\xa7\xc3\xa3o hist\xc3\xb3rica", "EXP-DOC-002"},
  {"CF88:ART.170:CAPUT|EXP-DOC-003", "Desigualdade para Todos", "DOCUMENT\xc3\x81RIO", 2013, 65,
   "O filme examina a dist\xc3\xa2ncia crescente entre as rendas dos ricos e dos pobres nos Estados Unidos.",
   "O filme examina a dist\xc3\xa2ncia crescente entre as rendas dos ricos e dos pobres nos Estados Unidos. A refer\xc3\xaancia ajuda a compreender a justi\xc3\xa7""a social e a exist\xc3\xaancia digna como finalidades da ordem econ\xc3\xb4mica. N\xc3\xa3o representa a organiza\xc3\xa7\xc3\xa3o integral da economia nem os instrumentos econ\xc3\xb4micos previstos nos incisos.",
   "a justi\xc3\xa7""a social e a exist\xc3\xaancia digna como finalidades da ordem econ\xc3\xb4mica", "Contextualiza\xc3\xa7\xc3\xa3o hist\xc3\xb3rica", "EXP-DOC-003"},
  {"CF88:ART.170:CAPUT|EXP-FIL-006", "Eu, Daniel Blake", "FILME", 2016, -1,
   "Katie, m\xc3\xa3""e de duas crian\xc3\xa7""as, e Daniel enfrentam falta de sustento e recorrem a banco alimentar.",
   "Katie, m\xc3\xa3""e de duas crian\xc3\xa7""as, e Daniel enfrentam falta de sustento e recorrem a banco alimentar. A refer\xc3\xaancia ajuda a compreender a justi\xc3\xa7""a social e a exist\xc3\xaancia digna como finalidades da ordem econ\xc3\xb4mica. N\xc3\xa3o representa a organiza\xc3\xa7\xc3\xa3o integral da economia nem os instrumentos econ\xc3\xb4micos previstos nos incisos.",
   "a justi\xc3\xa7""a social e a exist\xc3\xaancia digna como finalidades da ordem econ\xc3\xb4mica", "Ilustra\xc3\xa7\xc3\xa3o de consequ\xc3\xaancia", "EXP-FIL-006"},
  {"CF88:ART.170:CAPUT|EXP-LIV-009", "O Triunfo da Injusti\xc3\xa7""a", "LIVRO", 2019, -1,
   "Saez e Zucman analisam a queda relativa da tributa\xc3\xa7\xc3\xa3o dos mais ricos nos Estados Unidos e a desigualdade associada, propondo reformas.",
   "Saez e Zucman analisam a queda relativa da tributa\xc3\xa7\xc3\xa3o dos mais ricos nos Estados Unidos e a desigualdade associada, propondo reformas. A refer\xc3\xaancia ajuda a compreender a justi\xc3\xa7""a social e a exist\xc3\xaancia digna como finalidades da ordem econ\xc3\xb4mica. N\xc3\xa3o representa a organiza\xc3\xa7\xc3\xa3o integral da economia nem os instrumentos econ\xc3\xb4micos previstos nos incisos.",
   "a justi\xc3\xa7""a social e a exist\xc3\xaancia digna como finalidades da ordem econ\xc3\xb4mica", "Contextualiza\xc3\xa7\xc3\xa3o hist\xc3\xb3rica", "EXP-LIV-009"},
  {"CF88:ART.170:CAPUT|REF-DOC-0004", "Ilha das Flores", "DOCUMENT\xc3\x81RIO", 1989, -1,
   "Mulheres e crian\xc3\xa7""as sem recursos recolhem, em tempo limitado, os restos de alimento rejeitados para os porcos.",
   "Mulheres e crian\xc3\xa7""as sem recursos recolhem, em tempo limitado, os restos de alimento rejeitados para os porcos. A refer\xc3\xaancia ajuda a compreender a justi\xc3\xa7""a social e a exist\xc3\xaancia digna como finalidades da ordem econ\xc3\xb4mica. N\xc3\xa3o representa a organiza\xc3\xa7\xc3\xa3o integral da economia nem os instrumentos econ\xc3\xb4micos previstos nos incisos.",
   "a justi\xc3\xa7""a social e a exist\xc3\xaancia digna como finalidades da ordem econ\xc3\xb4mica", "Ilustra\xc3\xa7\xc3\xa3o de consequ\xc3\xaancia", "REF-DOC-0004"},
  {"CF88:ART.170:CAPUT|REF-LIV-0004", "Quarto de Despejo", "LIVRO", 1960, -1,
   "O di\xc3\xa1rio descreve a fome vivida por Carolina e seus filhos na favela do Canind\xc3\xa9.",
   "O di\xc3\xa1rio descreve a fome vivida por Carolina e seus filhos na favela do Canind\xc3\xa9. A refer\xc3\xaancia ajuda a compreender a justi\xc3\xa7""a social e a exist\xc3\xaancia digna como finalidades da ordem econ\xc3\xb4mica. N\xc3\xa3o representa a organiza\xc3\xa7\xc3\xa3o integral da economia nem os instrumentos econ\xc3\xb4micos previstos nos incisos.",
   "a justi\xc3\xa7""a social e a exist\xc3\xaancia digna como finalidades da ordem econ\xc3\xb4mica", "Ilustra\xc3\xa7\xc3\xa3o de consequ\xc3\xaancia", "REF-LIV-0004"},
  {"CF88:ART.170:INC.II|EXP-FIL-005", "Leviat\xc3\xa3", "FILME", 2014, 66,
   "Um prefeito corrupto tenta tomar o neg\xc3\xb3""cio, a casa e o terreno de Kolya, que recorre a um advogado.",
   "Um prefeito corrupto tenta tomar o neg\xc3\xb3""cio, a casa e o terreno de Kolya, que recorre a um advogado. A refer\xc3\xaancia ajuda a compreender a prote\xc3\xa7\xc3\xa3o da propriedade privada. N\xc3\xa3o demonstra todos os requisitos de interven\xc3\xa7\xc3\xa3o estatal ou de desapropria\xc3\xa7\xc3\xa3o no Brasil.",
   "a prote\xc3\xa7\xc3\xa3o da propriedade privada", "Ilustra\xc3\xa7\xc3\xa3o de viola\xc3\xa7\xc3\xa3o", "EXP-FIL-005"},
  {"CF88:ART.170:INC.VII|EXP-DOC-002", "Capital no S\xc3\xa9""culo XXI", "DOCUMENT\xc3\x81RIO", 2019, 58,
   "Baseado em Piketty, o document\xc3\xa1rio investiga a distribui\xc3\xa7\xc3\xa3o de riqueza e seus rendimentos.",
   "Baseado em Piketty, o document\xc3\xa1rio investiga a distribui\xc3\xa7\xc3\xa3o de riqueza e seus rendimentos. A refer\xc3\xaancia ajuda a compreender a redu\xc3\xa7\xc3\xa3o das desigualdades sociais. N\xc3\xa3o demonstra desigualdade regional espec\xc3\xad""fica nem um instrumento estatal de redu\xc3\xa7\xc3\xa3o da desigualdade.",
   "a redu\xc3\xa7\xc3\xa3o das desigualdades sociais", "Analogia controlada", "EXP-DOC-002"},
  {"CF88:ART.170:INC.VII|EXP-DOC-003", "Desigualdade para Todos", "DOCUMENT\xc3\x81RIO", 2013, 58,
   "O filme examina a dist\xc3\xa2ncia crescente entre as rendas dos ricos e dos pobres nos Estados Unidos.",
   "O filme examina a dist\xc3\xa2ncia crescente entre as rendas dos ricos e dos pobres nos Estados Unidos. A refer\xc3\xaancia ajuda a compreender a redu\xc3\xa7\xc3\xa3o das desigualdades sociais. N\xc3\xa3o demonstra desigualdade regional espec\xc3\xad""fica nem um instrumento estatal de redu\xc3\xa7\xc3\xa3o da desigualdade.",
   "a redu\xc3\xa7\xc3\xa3o das desigualdades sociais", "Analogia controlada", "EXP-DOC-003"},
  {"CF88:ART.170:INC.VII|EXP-FIL-006", "Eu, Daniel Blake", "FILME", 2016, 66,
   "Katie, m\xc3\xa3""e de duas crian\xc3\xa7""as, e Daniel enfrentam falta de sustento e recorrem a banco alimentar.",
   "Katie, m\xc3\xa3""e de duas crian\xc3\xa7""as, e Daniel enfrentam falta de sustento e recorrem a banco alimentar. A refer\xc3\xaancia ajuda a compreender a redu\xc3\xa7\xc3\xa3o das desigualdades sociais. N\xc3\xa3o demonstra desigualdade regional espec\xc3\xad""fica nem um instrumento estatal de redu\xc3\xa7\xc3\xa3o da desigualdade.",
   "a redu\xc3\xa7\xc3\xa3o das desigualdades sociais", "Ilustra\xc3\xa7\xc3\xa3o de consequ\xc3\xaancia", "EXP-FIL-006"},
  {"CF88:ART.170:INC.VII|EXP-LIV-009", "O Triunfo da Injusti\xc3\xa7""a", "LIVRO", 2019, -1,
   "Saez e Zucman analisam a queda relativa da tributa\xc3\xa7\xc3\xa3o dos mais ricos nos Estados Unidos e a desigualdade associada, propondo reformas.",
   "Saez e Zucman analisam a queda relativa da tributa\xc3\xa7\xc3\xa3o dos mais ricos nos Estados Unidos e a desigualdade associada, propondo reformas. A refer\xc3\xaancia ajuda a compreender a redu\xc3\xa7\xc3\xa3o das desigualdades sociais. N\xc3\xa3o demonstra desigualdade regional espec\xc3\xad""fica nem um instrumento estatal de redu\xc3\xa7\xc3\xa3o da desigualdade.",
   "a redu\xc3\xa7\xc3\xa3o das desigualdades sociais", "Analogia controlada", "EXP-LIV-009"},
  {"CF88:ART.170:INC.VII|REF-DOC-0004", "Ilha das Flores", "DOCUMENT\xc3\x81RIO", 1989, 78,
   "Mulheres e crian\xc3\xa7""as sem recursos recolhem, em tempo limitado, os restos de alimento rejeitados para os porcos.",
   "Mulheres e crian\xc3\xa7""as sem recursos recolhem, em tempo limitado, os restos de alimento rejeitados para os porcos. A refer\xc3\xaancia ajuda a compreender a redu\xc3\xa7\xc3\xa3o das desigualdades sociais. N\xc3\xa3o demonstra desigualdade regional espec\xc3\xad""fica nem um instrumento estatal de redu\xc3\xa7\xc3\xa3o da desigualdade.",
   "a redu\xc3\xa7\xc3\xa3o das desigualdades sociais", "Ilustra\xc3\xa7\xc3\xa3o de consequ\xc3\xaancia", "REF-DOC-0004"},
  {"CF88:ART.170:INC.VII|REF-LIV-0004", "Quarto de Despejo", "LIVRO", 1960, 83,
   "O di\xc3\xa1rio descreve a fome vivida por Carolina e seus filhos na favela do Canind\xc3\xa9.",
   "O di\xc3\xa1rio descreve a fome vivida por Carolina e seus filhos na favela do Canind\xc3\xa9. A refer\xc3\xaancia ajuda a compreender a redu\xc3\xa7\xc3\xa3o das desigualdades sociais. N\xc3\xa3o demonstra desigualdade regional espec\xc3\xad""fica nem um instrumento estatal de redu\xc3\xa7\xc3\xa3o da desigualdade.",
   "a redu\xc3\xa7\xc3\xa3o das desigualdades sociais", "Ilustra\xc3\xa7\xc3\xa3o de consequ\xc3\xaancia", "REF-LIV-0004"},
  {"CF88:ART.170:INC.VI|REF-FIL-0007", "O Pre\xc3\xa7o da Verdade", "FILME", 2019, 92,
   "A narrativa de Rob Bilott envolve disputa com a DuPont por toxinas PFOA que afetam pessoas e suas fam\xc3\xadlias.",
   "A narrativa de Rob Bilott envolve disputa com a DuPont por toxinas PFOA que afetam pessoas e suas fam\xc3\xadlias. A refer\xc3\xaancia ajuda a compreender a defesa do meio ambiente diante de atividades econ\xc3\xb4micas. N\xc3\xa3o demonstra o tratamento normativo diferenciado de produtos e processos segundo seu impacto ambiental.",
   "a defesa do meio ambiente diante de atividades econ\xc3\xb4micas", "Ilustra\xc3\xa7\xc3\xa3o de viola\xc3\xa7\xc3\xa3o", "REF-FIL-0007"},
  {"CF88:ART.170:INC.VI|REF-SER-0003", "Chernobyl", "S\xc3\x89RIE", 2019, 88,
   "A explos\xc3\xa3o da usina dispersa material radioativo por extensas \xc3\xa1reas europeias; a sinopse apresenta risco a milh\xc3\xb5""es de pessoas.",
   "A explos\xc3\xa3o da usina dispersa material radioativo por extensas \xc3\xa1reas europeias; a sinopse apresenta risco a milh\xc3\xb5""es de pessoas. A refer\xc3\xaancia ajuda a compreender a defesa do meio ambiente diante de atividades econ\xc3\xb4micas. N\xc3\xa3o demonstra o tratamento normativo diferenciado de produtos e processos segundo seu impacto ambiental.",
   "a defesa do meio ambiente diante de atividades econ\xc3\xb4micas", "Ilustra\xc3\xa7\xc3\xa3o de viola\xc3\xa7\xc3\xa3o", "REF-SER-0003"},
  {"CF88:ART.182:CAPUT|EXP-DOC-010", "Citizen Jane: Battle for the City", "DOCUMENT\xc3\x81RIO", 2016, 82,
   "Retrata a disputa de Jane Jacobs contra projetos urbanos de Robert Moses e a defesa da participa\xc3\xa7\xc3\xa3o comunit\xc3\xa1ria.",
   "O document\xc3\xa1rio mostra Jane Jacobs enfrentando projetos vi\xc3\xa1rios que destruiriam bairros de Nova York.",
   "Ajuda a compreender o que s\xc3\xa3o as \"fun\xc3\xa7\xc3\xb5""es sociais da cidade\" e a participa\xc3\xa7\xc3\xa3o dos moradores no planejamento. N\xc3\xa3o trata do plano diretor nem dos instrumentos do Estatuto da Cidade.\x0aLimites: Contexto norte-americano.", "", "EXP-DOC-010 \xc2\xb7 REFERENCE_EXPANSION_01"},
  {"CF88:ART.182:PAR.1|EXP-JOG-004", "Cities: Skylines", "JOGO", 2015, 76,
   "Simula\xc3\xa7\xc3\xa3o de constru\xc3\xa7\xc3\xa3o e gest\xc3\xa3o urbana com zoneamento, or\xc3\xa7""amento, servi\xc3\xa7os p\xc3\xba""blicos, transporte e tributa\xc3\xa7\xc3\xa3o local.",
   "O jogador planeja uma cidade inteira: zoneamento, transporte, servi\xc3\xa7os e expans\xc3\xa3o.",
   "Facilita visualizar o que um plano urbano organiza. N\xc3\xa3o reproduz exig\xc3\xaancias jur\xc3\xad""dicas (obrigatoriedade para cidades com mais de 20 mil habitantes, aprova\xc3\xa7\xc3\xa3o pela C\xc3\xa2mara).", "", "EXP-JOG-004 \xc2\xb7 REFERENCE_EXPANSION_01"},
  {"CF88:ART.184:CAPUT|EXP-DOC-008", "Cabra Marcado para Morrer", "DOCUMENT\xc3\x81RIO", 1984, 78,
   "Filme interrompido pelo golpe de 1964 e retomado para reconstruir a hist\xc3\xb3ria de l\xc3\xad""der campon\xc3\xaas e sua fam\xc3\xadlia.",
   "O filme retoma a hist\xc3\xb3ria de Jo\xc3\xa3o Pedro Teixeira, l\xc3\xad""der das Ligas Camponesas, e da luta por terra no Nordeste antes e depois de 1964.",
   "Ajuda a compreender a origem hist\xc3\xb3rica da reforma agr\xc3\xa1ria como tema constitucional. N\xc3\xa3o explica o procedimento de desapropria\xc3\xa7\xc3\xa3o nem a indeniza\xc3\xa7\xc3\xa3o em t\xc3\xadtulos.", "", "EXP-DOC-008 \xc2\xb7 REFERENCE_EXPANSION_01"},
  {"CF88:ART.192|EXP-FIL-007", "A Grande Aposta", "FILME", 2015, 78,
   "Dramatiza\xc3\xa7\xc3\xa3o de investidores que identificam a bolha hipotec\xc3\xa1ria e exp\xc3\xb5""em incentivos e falhas da crise financeira de 2008.",
   "O filme mostra como produtos financeiros de risco levaram \xc3\xa0 crise de 2008 e prejudicaram milh\xc3\xb5""es de pessoas.",
   "Ajuda a problematizar por que o sistema financeiro deve servir \xc3\xa0 coletividade e ser regulado. Contexto norte-americano; n\xc3\xa3o descreve o Banco Central nem as leis complementares do setor.\x0aLimites: Mercado norte-americano.", "", "EXP-FIL-007 \xc2\xb7 REFERENCE_EXPANSION_01"},
  {"CF88:ART.193:CAPUT|EXP-DOC-002", "Capital no S\xc3\xa9""culo XXI", "DOCUMENT\xc3\x81RIO", 2019, -1,
   "Baseado em Piketty, o document\xc3\xa1rio investiga a distribui\xc3\xa7\xc3\xa3o de riqueza e seus rendimentos.",
   "Baseado em Piketty, o document\xc3\xa1rio investiga a distribui\xc3\xa7\xc3\xa3o de riqueza e seus rendimentos. A refer\xc3\xaancia ajuda a compreender a justi\xc3\xa7""a social como objetivo da ordem social. N\xc3\xa3o representa conjuntamente todas as dimens\xc3\xb5""es do primado do trabalho, do bem-estar e da organiza\xc3\xa7\xc3\xa3o da ordem social.",
   "a justi\xc3\xa7""a social como objetivo da ordem social", "Analogia controlada", "EXP-DOC-002"},
  {"CF88:ART.193:CAPUT|EXP-DOC-003", "Desigualdade para Todos", "DOCUMENT\xc3\x81RIO", 2013, 68,
   "O filme examina a dist\xc3\xa2ncia crescente entre as rendas dos ricos e dos pobres nos Estados Unidos.",
   "O filme examina a dist\xc3\xa2ncia crescente entre as rendas dos ricos e dos pobres nos Estados Unidos. A refer\xc3\xaancia ajuda a compreender a justi\xc3\xa7""a social como objetivo da ordem social. N\xc3\xa3o representa conjuntamente todas as dimens\xc3\xb5""es do primado do trabalho, do bem-estar e da organiza\xc3\xa7\xc3\xa3o da ordem social.",
   "a justi\xc3\xa7""a social como objetivo da ordem social", "Analogia controlada", "EXP-DOC-003"},
  {"CF88:ART.193:CAPUT|EXP-LIV-009", "O Triunfo da Injusti\xc3\xa7""a", "LIVRO", 2019, -1,
   "Saez e Zucman analisam a queda relativa da tributa\xc3\xa7\xc3\xa3o dos mais ricos nos Estados Unidos e a desigualdade associada, propondo reformas.",
   "Saez e Zucman analisam a queda relativa da tributa\xc3\xa7\xc3\xa3o dos mais ricos nos Estados Unidos e a desigualdade associada, propondo reformas. A refer\xc3\xaancia ajuda a compreender a justi\xc3\xa7""a social como objetivo da ordem social. N\xc3\xa3o representa conjuntamente todas as dimens\xc3\xb5""es do primado do trabalho, do bem-estar e da organiza\xc3\xa7\xc3\xa3o da ordem social.",
   "a justi\xc3\xa7""a social como objetivo da ordem social", "Analogia controlada", "EXP-LIV-009"},
  {"CF88:ART.194:CAPUT|EXP-FIL-006", "Eu, Daniel Blake", "FILME", 2016, 60,
   "Ap\xc3\xb3s infarto e orienta\xc3\xa7\xc3\xa3o m\xc3\xa9""dica para n\xc3\xa3o trabalhar, Daniel \xc3\xa9 considerado apto pelo sistema de benef\xc3\xad""cios e precisa sobreviver nessa condi\xc3\xa7\xc3\xa3o.",
   "Ap\xc3\xb3s infarto e orienta\xc3\xa7\xc3\xa3o m\xc3\xa9""dica para n\xc3\xa3o trabalhar, Daniel \xc3\xa9 considerado apto pelo sistema de benef\xc3\xad""cios e precisa sobreviver nessa condi\xc3\xa7\xc3\xa3o. A refer\xc3\xaancia ajuda a compreender a prote\xc3\xa7\xc3\xa3o social diante da incapacidade para o trabalho, no \xc3\xa2mbito da seguridade social. N\xc3\xa3o demonstra recusa de servi\xc3\xa7o de sa\xc3\xba""de nem a organiza\xc3\xa7\xc3\xa3o integrada do sistema brasileiro de seguridade.",
   "a prote\xc3\xa7\xc3\xa3o social diante da incapacidade para o trabalho, no \xc3\xa2mbito da seguridade social", "Ilustra\xc3\xa7\xc3\xa3o de consequ\xc3\xaancia", "EXP-FIL-006"},
  {"CF88:ART.1:INC.III|EXP-FIL-006", "Eu, Daniel Blake", "FILME", 2016, 62,
   "Katie, m\xc3\xa3""e de duas crian\xc3\xa7""as, e Daniel enfrentam falta de sustento e recorrem a banco alimentar.",
   "Katie, m\xc3\xa3""e de duas crian\xc3\xa7""as, e Daniel enfrentam falta de sustento e recorrem a banco alimentar. A refer\xc3\xaancia ajuda a compreender a dignidade humana diante da priva\xc3\xa7\xc3\xa3o de condi\xc3\xa7\xc3\xb5""es materiais b\xc3\xa1sicas. N\xc3\xa3o atribui \xc3\xa0 obra cobertura de todas as dimens\xc3\xb5""es da dignidade humana.",
   "a dignidade humana diante da priva\xc3\xa7\xc3\xa3o de condi\xc3\xa7\xc3\xb5""es materiais b\xc3\xa1sicas", "Ilustra\xc3\xa7\xc3\xa3o de consequ\xc3\xaancia", "EXP-FIL-006"},
  {"CF88:ART.1:INC.III|REF-DOC-0004", "Ilha das Flores", "DOCUMENT\xc3\x81RIO", 1989, 92,
   "Mulheres e crian\xc3\xa7""as sem recursos recolhem, em tempo limitado, os restos de alimento rejeitados para os porcos.",
   "Mulheres e crian\xc3\xa7""as sem recursos recolhem, em tempo limitado, os restos de alimento rejeitados para os porcos. A refer\xc3\xaancia ajuda a compreender a dignidade humana diante da priva\xc3\xa7\xc3\xa3o de condi\xc3\xa7\xc3\xb5""es materiais b\xc3\xa1sicas. N\xc3\xa3o atribui \xc3\xa0 obra cobertura de todas as dimens\xc3\xb5""es da dignidade humana.",
   "a dignidade humana diante da priva\xc3\xa7\xc3\xa3o de condi\xc3\xa7\xc3\xb5""es materiais b\xc3\xa1sicas", "Ilustra\xc3\xa7\xc3\xa3o de consequ\xc3\xaancia", "REF-DOC-0004"},
  {"CF88:ART.1:INC.III|REF-JOG-0002", "This War of Mine", "JOGO", 2014, 76,
   "Civis sobrevivem em cidade sitiada, buscando comida e medicamentos escassos, sob riscos de viol\xc3\xaancia.",
   "Civis sobrevivem em cidade sitiada, buscando comida e medicamentos escassos, sob riscos de viol\xc3\xaancia. A refer\xc3\xaancia ajuda a compreender a dignidade humana diante da priva\xc3\xa7\xc3\xa3o de condi\xc3\xa7\xc3\xb5""es materiais b\xc3\xa1sicas. N\xc3\xa3o atribui \xc3\xa0 obra cobertura de todas as dimens\xc3\xb5""es da dignidade humana.",
   "a dignidade humana diante da priva\xc3\xa7\xc3\xa3o de condi\xc3\xa7\xc3\xb5""es materiais b\xc3\xa1sicas", "Ilustra\xc3\xa7\xc3\xa3o de consequ\xc3\xaancia", "REF-JOG-0002"},
  {"CF88:ART.1:INC.III|REF-LIV-0004", "Quarto de Despejo", "LIVRO", 1960, 92,
   "O di\xc3\xa1rio descreve a fome vivida por Carolina e seus filhos na favela do Canind\xc3\xa9.",
   "O di\xc3\xa1rio descreve a fome vivida por Carolina e seus filhos na favela do Canind\xc3\xa9. A refer\xc3\xaancia ajuda a compreender a dignidade humana diante da priva\xc3\xa7\xc3\xa3o de condi\xc3\xa7\xc3\xb5""es materiais b\xc3\xa1sicas. N\xc3\xa3o atribui \xc3\xa0 obra cobertura de todas as dimens\xc3\xb5""es da dignidade humana.",
   "a dignidade humana diante da priva\xc3\xa7\xc3\xa3o de condi\xc3\xa7\xc3\xb5""es materiais b\xc3\xa1sicas", "Ilustra\xc3\xa7\xc3\xa3o de consequ\xc3\xaancia", "REF-LIV-0004"},
  {"CF88:ART.1:INC.III|REF-LIV-0007", "Ensaio sobre a Cegueira", "LIVRO", 1995, 92,
   "No manic\xc3\xb4mio, um grupo de internos domina os demais e toma as ra\xc3\xa7\xc3\xb5""es de comida, privando-os do acesso livre \xc3\xa0 alimenta\xc3\xa7\xc3\xa3o.",
   "No manic\xc3\xb4mio, um grupo de internos domina os demais e toma as ra\xc3\xa7\xc3\xb5""es de comida, privando-os do acesso livre \xc3\xa0 alimenta\xc3\xa7\xc3\xa3o. A refer\xc3\xaancia ajuda a compreender a dignidade humana diante da priva\xc3\xa7\xc3\xa3o de condi\xc3\xa7\xc3\xb5""es materiais b\xc3\xa1sicas. N\xc3\xa3o atribui \xc3\xa0 obra cobertura de todas as dimens\xc3\xb5""es da dignidade humana.",
   "a dignidade humana diante da priva\xc3\xa7\xc3\xa3o de condi\xc3\xa7\xc3\xb5""es materiais b\xc3\xa1sicas", "Ilustra\xc3\xa7\xc3\xa3o de consequ\xc3\xaancia", "REF-LIV-0007"},
  {"CF88:ART.1:INC.III|REF-SER-0002", "The Handmaid's Tale", "S\xc3\x89RIE", 2017, 88,
   "Mulheres f\xc3\xa9rteis s\xc3\xa3o submetidas \xc3\xa0 servid\xc3\xa3o reprodutiva em Gilead.",
   "Mulheres f\xc3\xa9rteis s\xc3\xa3o submetidas \xc3\xa0 servid\xc3\xa3o reprodutiva em Gilead. A refer\xc3\xaancia ajuda a compreender a dignidade humana diante da servid\xc3\xa3o reprodutiva. N\xc3\xa3o atribui \xc3\xa0 obra cobertura de todas as dimens\xc3\xb5""es da dignidade humana.",
   "a dignidade humana diante da servid\xc3\xa3o reprodutiva", "Ilustra\xc3\xa7\xc3\xa3o de viola\xc3\xa7\xc3\xa3o", "REF-SER-0002"},
  {"CF88:ART.1:PAR.UNICO|REF-FIL-0005", "Selma", "FILME", 2014, -1,
   "A narrativa acompanha a mobiliza\xc3\xa7\xc3\xa3o de King e a marcha de Selma a Montgomery pelo movimento de direitos civis.",
   "A narrativa acompanha a mobiliza\xc3\xa7\xc3\xa3o de King e a marcha de Selma a Montgomery pelo movimento de direitos civis. A refer\xc3\xaancia ajuda a compreender a participa\xc3\xa7\xc3\xa3o dos governados no exerc\xc3\xad""cio do poder pol\xc3\xadtico. N\xc3\xa3o descreve todas as formas constitucionais de representa\xc3\xa7\xc3\xa3o e participa\xc3\xa7\xc3\xa3o direta.",
   "a participa\xc3\xa7\xc3\xa3o dos governados no exerc\xc3\xad""cio do poder pol\xc3\xadtico", "Contextualiza\xc3\xa7\xc3\xa3o hist\xc3\xb3rica", "REF-FIL-0005"},
  {"CF88:ART.201:INC.I|EXP-FIL-006", "Eu, Daniel Blake", "FILME", 2016, 84,
   "Carpinteiro impedido de trabalhar enfrenta a burocracia do sistema de benef\xc3\xad""cios sociais ap\xc3\xb3s problema de sa\xc3\xba""de.",
   "Daniel, impedido de trabalhar ap\xc3\xb3s um infarto, enfrenta a per\xc3\xad""cia e a burocracia para obter o benef\xc3\xad""cio por incapacidade. O inciso I p\xc3\xb5""e a incapacidade para o trabalho entre os riscos cobertos pela previd\xc3\xaancia.",
   "Ajuda a visualizar o que \xc3\xa9 o risco social \"incapacidade para o trabalho\" e por que a previd\xc3\xaancia existe para cobri-lo. N\xc3\xa3o demonstra os requisitos do RGPS brasileiro (car\xc3\xaancia, qualidade de segurado, per\xc3\xad""cia do INSS).\x0aLimites: Sistema brit\xc3\xa2nico de benef\xc3\xad""cios; n\xc3\xa3o equivale ao RGPS.", "", "EXP-FIL-006 \xc2\xb7 REFERENCE_EXPANSION_01"},
  {"CF88:ART.203:INC.VI|EXP-FIL-006", "Eu, Daniel Blake", "FILME", 2016, 62,
   "Katie, m\xc3\xa3""e de duas crian\xc3\xa7""as, e Daniel enfrentam falta de sustento e recorrem a banco alimentar.",
   "Katie, m\xc3\xa3""e de duas crian\xc3\xa7""as, e Daniel enfrentam falta de sustento e recorrem a banco alimentar. A refer\xc3\xaancia ajuda a compreender a vulnerabilidade socioecon\xc3\xb4mica de fam\xc3\xadlias pobres que a assist\xc3\xaancia social busca reduzir. N\xc3\xa3o retrata implementa\xc3\xa7\xc3\xa3o, compet\xc3\xaancia ou funcionamento de programa assistencial brasileiro.",
   "a vulnerabilidade socioecon\xc3\xb4mica de fam\xc3\xadlias pobres que a assist\xc3\xaancia social busca reduzir", "Ilustra\xc3\xa7\xc3\xa3o de consequ\xc3\xaancia", "EXP-FIL-006"},
  {"CF88:ART.203:INC.VI|REF-DOC-0004", "Ilha das Flores", "DOCUMENT\xc3\x81RIO", 1989, 75,
   "Mulheres e crian\xc3\xa7""as sem recursos recolhem, em tempo limitado, os restos de alimento rejeitados para os porcos.",
   "Mulheres e crian\xc3\xa7""as sem recursos recolhem, em tempo limitado, os restos de alimento rejeitados para os porcos. A refer\xc3\xaancia ajuda a compreender a vulnerabilidade socioecon\xc3\xb4mica de fam\xc3\xadlias pobres que a assist\xc3\xaancia social busca reduzir. N\xc3\xa3o retrata implementa\xc3\xa7\xc3\xa3o, compet\xc3\xaancia ou funcionamento de programa assistencial brasileiro.",
   "a vulnerabilidade socioecon\xc3\xb4mica de fam\xc3\xadlias pobres que a assist\xc3\xaancia social busca reduzir", "Ilustra\xc3\xa7\xc3\xa3o de consequ\xc3\xaancia", "REF-DOC-0004"},
  {"CF88:ART.203:INC.VI|REF-LIV-0004", "Quarto de Despejo", "LIVRO", 1960, 83,
   "O di\xc3\xa1rio descreve a fome vivida por Carolina e seus filhos na favela do Canind\xc3\xa9.",
   "O di\xc3\xa1rio descreve a fome vivida por Carolina e seus filhos na favela do Canind\xc3\xa9. A refer\xc3\xaancia ajuda a compreender a vulnerabilidade socioecon\xc3\xb4mica de fam\xc3\xadlias pobres que a assist\xc3\xaancia social busca reduzir. N\xc3\xa3o retrata implementa\xc3\xa7\xc3\xa3o, compet\xc3\xaancia ou funcionamento de programa assistencial brasileiro.",
   "a vulnerabilidade socioecon\xc3\xb4mica de fam\xc3\xadlias pobres que a assist\xc3\xaancia social busca reduzir", "Ilustra\xc3\xa7\xc3\xa3o de consequ\xc3\xaancia", "REF-LIV-0004"},
  {"CF88:ART.205:CAPUT|EXP-LIV-004", "Cidadania no Brasil: O Longo Caminho", "LIVRO", 2001, 69,
   "Carvalho analisa historicamente a educa\xc3\xa7\xc3\xa3o popular como condi\xc3\xa7\xc3\xa3o de conhecimento e expans\xc3\xa3o de direitos civis e pol\xc3\xadticos.",
   "Carvalho analisa historicamente a educa\xc3\xa7\xc3\xa3o popular como condi\xc3\xa7\xc3\xa3o de conhecimento e expans\xc3\xa3o de direitos civis e pol\xc3\xadticos. A refer\xc3\xaancia ajuda a compreender o direito \xc3\xa0 educa\xc3\xa7\xc3\xa3o e sua fun\xc3\xa7\xc3\xa3o na forma\xc3\xa7\xc3\xa3o da cidadania. N\xc3\xa3o demonstra realiza\xc3\xa7\xc3\xa3o de todas as finalidades de desenvolvimento pessoal, preparo para cidadania e qualifica\xc3\xa7\xc3\xa3o profissional.",
   "o direito \xc3\xa0 educa\xc3\xa7\xc3\xa3o e sua fun\xc3\xa7\xc3\xa3o na forma\xc3\xa7\xc3\xa3o da cidadania", "Contextualiza\xc3\xa7\xc3\xa3o hist\xc3\xb3rica", "EXP-LIV-004"},
  {"CF88:ART.215:PAR.1|EXP-JOG-006", "Never Alone (Kisima In\xc5\x8bitchu\xc5\x8b""a)", "JOGO", 2014, 74,
   "Jogo de plataforma produzido com anci\xc3\xa3os e narradores I\xc3\xb1upiat, baseado em hist\xc3\xb3rias e valores culturais da comunidade.",
   "O jogo foi criado com a comunidade I\xc3\xb1upiat e transmite suas hist\xc3\xb3rias tradicionais.",
   "Ajuda a compreender o que \xc3\xa9 proteger manifesta\xc3\xa7\xc3\xa3o cultural de um povo ind\xc3\xadgena. Contexto do Alasca; n\xc3\xa3o trata de pol\xc3\xadticas culturais brasileiras.\x0aLimites: Povo ind\xc3\xadgena do Alasca, n\xc3\xa3o brasileiro.", "", "EXP-JOG-006 \xc2\xb7 REFERENCE_EXPANSION_01"},
  {"CF88:ART.220:CAPUT|REF-FIL-0006", "The Post: A Guerra Secreta", "FILME", 2017, 84,
   "Editora e editor do Washington Post exp\xc3\xb5""em segredos governamentais por meio dos Pentagon Papers, arriscando carreira e liberdade.",
   "Editora e editor do Washington Post exp\xc3\xb5""em segredos governamentais por meio dos Pentagon Papers, arriscando carreira e liberdade. A refer\xc3\xaancia ajuda a compreender a liberdade de informa\xc3\xa7\xc3\xa3o e de comunica\xc3\xa7\xc3\xa3o. N\xc3\xa3o demonstra todas as condi\xc3\xa7\xc3\xb5""es e responsabilidades constitucionais da comunica\xc3\xa7\xc3\xa3o social.",
   "a liberdade de informa\xc3\xa7\xc3\xa3o e de comunica\xc3\xa7\xc3\xa3o", "Representa\xc3\xa7\xc3\xa3o", "REF-FIL-0006"},
  {"CF88:ART.220:PAR.2|REF-FIL-0002", "V de Vingan\xc3\xa7""a", "FILME", 2005, 85,
   "As notas de produ\xc3\xa7\xc3\xa3o do filme descrevem a morte dos pais de Evey por se manifestarem contra o regime repressivo.",
   "As notas de produ\xc3\xa7\xc3\xa3o do filme descrevem a morte dos pais de Evey por se manifestarem contra o regime repressivo. A refer\xc3\xaancia ajuda a compreender a prote\xc3\xa7\xc3\xa3o contra a censura pol\xc3\xadtica ou ideol\xc3\xb3gica. N\xc3\xa3o afirma que a evid\xc3\xaancia alcance tamb\xc3\xa9m censura art\xc3\xadstica.",
   "a prote\xc3\xa7\xc3\xa3o contra a censura pol\xc3\xadtica ou ideol\xc3\xb3gica", "Ilustra\xc3\xa7\xc3\xa3o de viola\xc3\xa7\xc3\xa3o", "REF-FIL-0002"},
  {"CF88:ART.220:PAR.2|REF-FIL-0006", "The Post: A Guerra Secreta", "FILME", 2017, 92,
   "A administra\xc3\xa7\xc3\xa3o Nixon tenta restringir a divulga\xc3\xa7\xc3\xa3o jornal\xc3\xadstica dos Pentagon Papers; os editores enfrentam a medida para publicar informa\xc3\xa7\xc3\xb5""es cr\xc3\xadticas ao governo.",
   "A administra\xc3\xa7\xc3\xa3o Nixon tenta restringir a divulga\xc3\xa7\xc3\xa3o jornal\xc3\xadstica dos Pentagon Papers; os editores enfrentam a medida para publicar informa\xc3\xa7\xc3\xb5""es cr\xc3\xadticas ao governo. A refer\xc3\xaancia ajuda a compreender a prote\xc3\xa7\xc3\xa3o contra a censura pol\xc3\xadtica ou ideol\xc3\xb3gica. N\xc3\xa3o afirma que a evid\xc3\xaancia alcance tamb\xc3\xa9m censura art\xc3\xadstica.",
   "a prote\xc3\xa7\xc3\xa3o contra a censura pol\xc3\xadtica ou ideol\xc3\xb3gica", "Ilustra\xc3\xa7\xc3\xa3o de viola\xc3\xa7\xc3\xa3o", "REF-FIL-0006"},
  {"CF88:ART.220:PAR.2|REF-LIV-0001", "1984", "LIVRO", 1949, 83,
   "O Partido pro\xc3\xad""be express\xc3\xa3o dissidente; Winston registra pensamentos e discute sua derrubada, sendo capturado e reeducado pela Pol\xc3\xad""cia do Pensamento.",
   "O Partido pro\xc3\xad""be express\xc3\xa3o dissidente; Winston registra pensamentos e discute sua derrubada, sendo capturado e reeducado pela Pol\xc3\xad""cia do Pensamento. A refer\xc3\xaancia ajuda a compreender a prote\xc3\xa7\xc3\xa3o contra a censura pol\xc3\xadtica ou ideol\xc3\xb3gica. N\xc3\xa3o afirma que a evid\xc3\xaancia alcance tamb\xc3\xa9m censura art\xc3\xadstica.",
   "a prote\xc3\xa7\xc3\xa3o contra a censura pol\xc3\xadtica ou ideol\xc3\xb3gica", "Ilustra\xc3\xa7\xc3\xa3o de viola\xc3\xa7\xc3\xa3o", "REF-LIV-0001"},
  {"CF88:ART.225:CAPUT|REF-FIL-0007", "O Pre\xc3\xa7o da Verdade", "FILME", 2019, 88,
   "A narrativa de Rob Bilott envolve disputa com a DuPont por toxinas PFOA que afetam pessoas e suas fam\xc3\xadlias.",
   "A narrativa de Rob Bilott envolve disputa com a DuPont por toxinas PFOA que afetam pessoas e suas fam\xc3\xadlias. A refer\xc3\xaancia ajuda a compreender o direito ao meio ambiente equilibrado e a necessidade de proteg\xc3\xaa-lo. N\xc3\xa3o demonstra todas as obriga\xc3\xa7\xc3\xb5""es dos Poderes P\xc3\xba""blicos nem os instrumentos e san\xc3\xa7\xc3\xb5""es dos par\xc3\xa1grafos.",
   "o direito ao meio ambiente equilibrado e a necessidade de proteg\xc3\xaa-lo", "Ilustra\xc3\xa7\xc3\xa3o de viola\xc3\xa7\xc3\xa3o", "REF-FIL-0007"},
  {"CF88:ART.225:CAPUT|REF-SER-0003", "Chernobyl", "S\xc3\x89RIE", 2019, 84,
   "A explos\xc3\xa3o da usina dispersa material radioativo por extensas \xc3\xa1reas europeias; a sinopse apresenta risco a milh\xc3\xb5""es de pessoas.",
   "A explos\xc3\xa3o da usina dispersa material radioativo por extensas \xc3\xa1reas europeias; a sinopse apresenta risco a milh\xc3\xb5""es de pessoas. A refer\xc3\xaancia ajuda a compreender o direito ao meio ambiente equilibrado e a necessidade de proteg\xc3\xaa-lo. N\xc3\xa3o demonstra todas as obriga\xc3\xa7\xc3\xb5""es dos Poderes P\xc3\xba""blicos nem os instrumentos e san\xc3\xa7\xc3\xb5""es dos par\xc3\xa1grafos.",
   "o direito ao meio ambiente equilibrado e a necessidade de proteg\xc3\xaa-lo", "Ilustra\xc3\xa7\xc3\xa3o de viola\xc3\xa7\xc3\xa3o", "REF-SER-0003"},
  {"CF88:ART.226:PAR.7|REF-SER-0002", "The Handmaid's Tale", "S\xc3\x89RIE", 2017, 75,
   "Mulheres f\xc3\xa9rteis s\xc3\xa3o submetidas \xc3\xa0 servid\xc3\xa3o reprodutiva em Gilead.",
   "Mulheres f\xc3\xa9rteis s\xc3\xa3o submetidas \xc3\xa0 servid\xc3\xa3o reprodutiva em Gilead. A refer\xc3\xaancia ajuda a compreender a liberdade de decis\xc3\xa3o reprodutiva e a veda\xc3\xa7\xc3\xa3o \xc3\xa0 coer\xc3\xa7\xc3\xa3o no planejamento familiar. N\xc3\xa3o demonstra a oferta estatal de recursos educacionais e cient\xc3\xad""ficos nem todo o regime brasileiro de planejamento familiar.",
   "a liberdade de decis\xc3\xa3o reprodutiva e a veda\xc3\xa7\xc3\xa3o \xc3\xa0 coer\xc3\xa7\xc3\xa3o no planejamento familiar", "Ilustra\xc3\xa7\xc3\xa3o de viola\xc3\xa7\xc3\xa3o", "REF-SER-0002"},
  {"CF88:ART.227:CAPUT|REF-LIV-0004", "Quarto de Despejo", "LIVRO", 1960, 74,
   "O di\xc3\xa1rio descreve a fome vivida por Carolina e seus filhos na favela do Canind\xc3\xa9.",
   "O di\xc3\xa1rio descreve a fome vivida por Carolina e seus filhos na favela do Canind\xc3\xa9. A refer\xc3\xaancia ajuda a compreender a prote\xc3\xa7\xc3\xa3o priorit\xc3\xa1ria da alimenta\xc3\xa7\xc3\xa3o de crian\xc3\xa7""as. A evid\xc3\xaancia \xc3\xa9 a fome dos filhos; n\xc3\xa3o demonstra viola\xc3\xa7\xc3\xa3o aut\xc3\xb4noma dos demais direitos enumerados, como sa\xc3\xba""de, educa\xc3\xa7\xc3\xa3o e conviv\xc3\xaancia familiar.\x0aO di\xc3\xa1rio descreve a fome vivida por Carolina e seus filhos na favela do Canind\xc3\xa9. A refer\xc3\xaancia ajuda a compreender o direito de crian\xc3\xa7""as \xc3\xa0 alimenta\xc3\xa7\xc3\xa3o entre os direitos protegidos pelo art. 227. A evid\xc3\xaancia \xc3\xa9 a fome dos filhos; n\xc3\xa3o demonstra viola\xc3\xa7\xc3\xa3o aut\xc3\xb4noma dos demais direitos enumerados, como sa\xc3\xba""de, educa\xc3\xa7\xc3\xa3o e conviv\xc3\xaancia familiar.",
   "a prote\xc3\xa7\xc3\xa3o priorit\xc3\xa1ria da alimenta\xc3\xa7\xc3\xa3o de crian\xc3\xa7""as; o direito de crian\xc3\xa7""as \xc3\xa0 alimenta\xc3\xa7\xc3\xa3o entre os direitos protegidos pelo art. 227", "Ilustra\xc3\xa7\xc3\xa3o de viola\xc3\xa7\xc3\xa3o", "REF-LIV-0004"},
  {"CF88:ART.231:CAPUT|EXP-DOC-007", "Mart\xc3\xadrio", "DOCUMENT\xc3\x81RIO", 2016, 86,
   "Documenta a resist\xc3\xaancia Guarani-Kaiow\xc3\xa1, retomadas territoriais e viol\xc3\xaancia hist\xc3\xb3rica.",
   "O document\xc3\xa1rio acompanha a luta dos Guarani-Kaiow\xc3\xa1 pela retomada de terras tradicionais no Mato Grosso do Sul.",
   "Ajuda a compreender o que s\xc3\xa3o terras tradicionalmente ocupadas e por que a demarca\xc3\xa7\xc3\xa3o \xc3\xa9 central. N\xc3\xa3o trata do regime jur\xc3\xad""dico detalhado da demarca\xc3\xa7\xc3\xa3o.", "", "EXP-DOC-007 \xc2\xb7 REFERENCE_EXPANSION_01"},
  {"CF88:ART.23:INC.IX|EXP-SER-006", "Show Me a Hero", "S\xc3\x89RIE", 2015, 77,
   "A constru\xc3\xa7\xc3\xa3o de moradias de dessegrega\xc3\xa7\xc3\xa3o come\xc3\xa7""a enquanto o prefeito enfrenta oposi\xc3\xa7\xc3\xa3o local; moradores s\xc3\xa3o selecionados para as unidades.",
   "A constru\xc3\xa7\xc3\xa3o de moradias de dessegrega\xc3\xa7\xc3\xa3o come\xc3\xa7""a enquanto o prefeito enfrenta oposi\xc3\xa7\xc3\xa3o local; moradores s\xc3\xa3o selecionados para as unidades. A refer\xc3\xaancia ajuda a compreender a constru\xc3\xa7\xc3\xa3o de moradias por meio de programa habitacional. N\xc3\xa3o demonstra saneamento b\xc3\xa1sico nem a distribui\xc3\xa7\xc3\xa3o constitucional brasileira de compet\xc3\xaancias.",
   "a constru\xc3\xa7\xc3\xa3o de moradias por meio de programa habitacional", "Analogia controlada", "EXP-SER-006"},
  {"CF88:ART.2:CAPUT|EXP-LIV-006", "O Federalista", "LIVRO", 1788, -1,
   "Madison defende a distin\xc3\xa7\xc3\xa3o dos poderes legislativo, executivo e judici\xc3\xa1rio e, no ensaio seguinte, controles constitucionais rec\xc3\xadprocos.",
   "Madison defende a distin\xc3\xa7\xc3\xa3o dos poderes legislativo, executivo e judici\xc3\xa1rio e, no ensaio seguinte, controles constitucionais rec\xc3\xadprocos. A refer\xc3\xaancia ajuda a compreender a separa\xc3\xa7\xc3\xa3o dos poderes e seus controles rec\xc3\xadprocos. N\xc3\xa3o equipara a organiza\xc3\xa7\xc3\xa3o institucional estrangeira \xc3\xa0 Constitui\xc3\xa7\xc3\xa3o brasileira.",
   "a separa\xc3\xa7\xc3\xa3o dos poderes e seus controles rec\xc3\xadprocos", "Analogia controlada", "EXP-LIV-006"},
  {"CF88:ART.37:CAPUT|EXP-LIV-001", "Ra\xc3\xadzes do Brasil", "LIVRO", 1936, 80,
   "Ensaio cl\xc3\xa1ssico sobre forma\xc3\xa7\xc3\xa3o social brasileira, personalismo e dificuldades da institucionaliza\xc3\xa7\xc3\xa3o democr\xc3\xa1tica.",
   "S\xc3\xa9rgio Buarque descreve o \"homem cordial\" e a dificuldade de separar rela\xc3\xa7\xc3\xb5""es pessoais e fun\xc3\xa7\xc3\xa3o p\xc3\xba""blica. A impessoalidade do art. 37 exige justamente essa separa\xc3\xa7\xc3\xa3o.",
   "Facilita lembrar o sentido da impessoalidade (agir pelo cargo, n\xc3\xa3o por afeto ou parentesco). N\xc3\xa3o aborda os demais princ\xc3\xadpios nem as regras de concurso, nepotismo ou improbidade.\x0aLimites: A express\xc3\xa3o \"homem cordial\" costuma ser mal lida como \"gentil\"; a ficha deve evitar esse equ\xc3\xadvoco.", "", "EXP-LIV-001 \xc2\xb7 REFERENCE_EXPANSION_01"},
  {"CF88:ART.37:CAPUT|EXP-LIV-002", "Os Donos do Poder", "LIVRO", 1958, 86,
   "Interpreta\xc3\xa7\xc3\xa3o hist\xc3\xb3rica do patrimonialismo e do estamento burocr\xc3\xa1tico na forma\xc3\xa7\xc3\xa3o do Estado brasileiro.",
   "Faoro descreve o patrimonialismo: o Estado tratado como extens\xc3\xa3o dos interesses de um estamento que o controla. O caput do art. 37 \xc3\xa9 a resposta normativa a isso: a administra\xc3\xa7\xc3\xa3o deve agir para todos, sem favorecimentos pessoais.",
   "Ajuda a compreender por que impessoalidade e moralidade s\xc3\xa3o princ\xc3\xadpios expressos: o leitor visualiza o problema hist\xc3\xb3rico (confus\xc3\xa3o entre p\xc3\xba""blico e privado) que eles combatem. N\xc3\xa3o explica o regime jur\xc3\xad""dico de cada princ\xc3\xadpio nem a legalidade, a publicidade e a efici\xc3\xaancia.", "", "EXP-LIV-002 \xc2\xb7 REFERENCE_EXPANSION_01"},
  {"CF88:ART.3:INC.III|EXP-DOC-002", "Capital no S\xc3\xa9""culo XXI", "DOCUMENT\xc3\x81RIO", 2019, 58,
   "Baseado em Piketty, o document\xc3\xa1rio investiga a distribui\xc3\xa7\xc3\xa3o de riqueza e seus rendimentos.",
   "Baseado em Piketty, o document\xc3\xa1rio investiga a distribui\xc3\xa7\xc3\xa3o de riqueza e seus rendimentos. A refer\xc3\xaancia ajuda a compreender a redu\xc3\xa7\xc3\xa3o das desigualdades sociais. N\xc3\xa3o demonstra especificamente desigualdades regionais nem a execu\xc3\xa7\xc3\xa3o de medidas brasileiras.",
   "a redu\xc3\xa7\xc3\xa3o das desigualdades sociais", "Analogia controlada", "EXP-DOC-002"},
  {"CF88:ART.3:INC.III|EXP-DOC-003", "Desigualdade para Todos", "DOCUMENT\xc3\x81RIO", 2013, 58,
   "O filme examina a dist\xc3\xa2ncia crescente entre as rendas dos ricos e dos pobres nos Estados Unidos.",
   "O filme examina a dist\xc3\xa2ncia crescente entre as rendas dos ricos e dos pobres nos Estados Unidos. A refer\xc3\xaancia ajuda a compreender a redu\xc3\xa7\xc3\xa3o das desigualdades sociais. N\xc3\xa3o demonstra especificamente desigualdades regionais nem a execu\xc3\xa7\xc3\xa3o de medidas brasileiras.",
   "a redu\xc3\xa7\xc3\xa3o das desigualdades sociais", "Analogia controlada", "EXP-DOC-003"},
  {"CF88:ART.3:INC.III|EXP-FIL-006", "Eu, Daniel Blake", "FILME", 2016, 66,
   "Katie, m\xc3\xa3""e de duas crian\xc3\xa7""as, e Daniel enfrentam falta de sustento e recorrem a banco alimentar.",
   "Katie, m\xc3\xa3""e de duas crian\xc3\xa7""as, e Daniel enfrentam falta de sustento e recorrem a banco alimentar. A refer\xc3\xaancia ajuda a compreender o enfrentamento da pobreza e da marginaliza\xc3\xa7\xc3\xa3o social. N\xc3\xa3o demonstra execu\xc3\xa7\xc3\xa3o de pol\xc3\xadtica p\xc3\xba""blica ou erradica\xc3\xa7\xc3\xa3o efetiva desses problemas.",
   "o enfrentamento da pobreza e da marginaliza\xc3\xa7\xc3\xa3o social", "Ilustra\xc3\xa7\xc3\xa3o de consequ\xc3\xaancia", "EXP-FIL-006"},
  {"CF88:ART.3:INC.III|EXP-LIV-009", "O Triunfo da Injusti\xc3\xa7""a", "LIVRO", 2019, -1,
   "Saez e Zucman analisam a queda relativa da tributa\xc3\xa7\xc3\xa3o dos mais ricos nos Estados Unidos e a desigualdade associada, propondo reformas.",
   "Saez e Zucman analisam a queda relativa da tributa\xc3\xa7\xc3\xa3o dos mais ricos nos Estados Unidos e a desigualdade associada, propondo reformas. A refer\xc3\xaancia ajuda a compreender a redu\xc3\xa7\xc3\xa3o das desigualdades sociais. N\xc3\xa3o demonstra especificamente desigualdades regionais nem a execu\xc3\xa7\xc3\xa3o de medidas brasileiras.",
   "a redu\xc3\xa7\xc3\xa3o das desigualdades sociais", "Analogia controlada", "EXP-LIV-009"},
  {"CF88:ART.3:INC.III|REF-DOC-0004", "Ilha das Flores", "DOCUMENT\xc3\x81RIO", 1989, 78,
   "Mulheres e crian\xc3\xa7""as sem recursos recolhem, em tempo limitado, os restos de alimento rejeitados para os porcos.",
   "Mulheres e crian\xc3\xa7""as sem recursos recolhem, em tempo limitado, os restos de alimento rejeitados para os porcos. A refer\xc3\xaancia ajuda a compreender o enfrentamento da pobreza e da marginaliza\xc3\xa7\xc3\xa3o social. N\xc3\xa3o demonstra execu\xc3\xa7\xc3\xa3o de pol\xc3\xadtica p\xc3\xba""blica ou erradica\xc3\xa7\xc3\xa3o efetiva desses problemas.",
   "o enfrentamento da pobreza e da marginaliza\xc3\xa7\xc3\xa3o social", "Ilustra\xc3\xa7\xc3\xa3o de consequ\xc3\xaancia", "REF-DOC-0004"},
  {"CF88:ART.3:INC.III|REF-LIV-0004", "Quarto de Despejo", "LIVRO", 1960, 83,
   "O di\xc3\xa1rio descreve a fome vivida por Carolina e seus filhos na favela do Canind\xc3\xa9.",
   "O di\xc3\xa1rio descreve a fome vivida por Carolina e seus filhos na favela do Canind\xc3\xa9. A refer\xc3\xaancia ajuda a compreender o enfrentamento da pobreza e da marginaliza\xc3\xa7\xc3\xa3o social. N\xc3\xa3o demonstra execu\xc3\xa7\xc3\xa3o de pol\xc3\xadtica p\xc3\xba""blica ou erradica\xc3\xa7\xc3\xa3o efetiva desses problemas.",
   "o enfrentamento da pobreza e da marginaliza\xc3\xa7\xc3\xa3o social", "Ilustra\xc3\xa7\xc3\xa3o de consequ\xc3\xaancia", "REF-LIV-0004"},
  {"CF88:ART.3:INC.IV|EXP-DOC-009", "AmarElo \xe2\x80\x94 \xc3\x89 Tudo Pra Ontem", "DOCUMENT\xc3\x81RIO", 2020, 84,
   "Guilherme Wisnik analisa o document\xc3\xa1rio como den\xc3\xbancia do racismo estrutural brasileiro.",
   "Guilherme Wisnik analisa o document\xc3\xa1rio como den\xc3\xbancia do racismo estrutural brasileiro. A refer\xc3\xaancia ajuda a compreender o combate ao preconceito e \xc3\xa0 discrimina\xc3\xa7\xc3\xa3o racial. N\xc3\xa3o demonstra todas as esp\xc3\xa9""cies de discrimina\xc3\xa7\xc3\xa3o enumeradas no dispositivo.",
   "o combate ao preconceito e \xc3\xa0 discrimina\xc3\xa7\xc3\xa3o racial", "Ilustra\xc3\xa7\xc3\xa3o de viola\xc3\xa7\xc3\xa3o", "EXP-DOC-009"},
  {"CF88:ART.3:INC.IV|EXP-LIV-008", "A Cor da Lei", "LIVRO", 2017, -1,
   "Rothstein analisa como pol\xc3\xadticas federais, estaduais e locais produziram segrega\xc3\xa7\xc3\xa3o residencial.",
   "Rothstein analisa como pol\xc3\xadticas federais, estaduais e locais produziram segrega\xc3\xa7\xc3\xa3o residencial. A refer\xc3\xaancia ajuda a compreender o combate ao preconceito e \xc3\xa0 discrimina\xc3\xa7\xc3\xa3o racial. N\xc3\xa3o demonstra todas as esp\xc3\xa9""cies de discrimina\xc3\xa7\xc3\xa3o enumeradas no dispositivo.",
   "o combate ao preconceito e \xc3\xa0 discrimina\xc3\xa7\xc3\xa3o racial", "Ilustra\xc3\xa7\xc3\xa3o de viola\xc3\xa7\xc3\xa3o", "EXP-LIV-008"},
  {"CF88:ART.3:INC.IV|EXP-LIV-010", "Borderlands/La Frontera: The New Mestiza", "LIVRO", 1987, 80,
   "A resenha acad\xc3\xaamica relaciona a epistemologia de Borderlands \xc3\xa0 cr\xc3\xadtica da naturaliza\xc3\xa7\xc3\xa3o do racismo na vida americana.",
   "A resenha acad\xc3\xaamica relaciona a epistemologia de Borderlands \xc3\xa0 cr\xc3\xadtica da naturaliza\xc3\xa7\xc3\xa3o do racismo na vida americana. A refer\xc3\xaancia ajuda a compreender o combate ao preconceito e \xc3\xa0 discrimina\xc3\xa7\xc3\xa3o racial. N\xc3\xa3o demonstra todas as esp\xc3\xa9""cies de discrimina\xc3\xa7\xc3\xa3o enumeradas no dispositivo.",
   "o combate ao preconceito e \xc3\xa0 discrimina\xc3\xa7\xc3\xa3o racial", "Ilustra\xc3\xa7\xc3\xa3o de viola\xc3\xa7\xc3\xa3o", "EXP-LIV-010"},
  {"CF88:ART.3:INC.IV|EXP-SER-006", "Show Me a Hero", "S\xc3\x89RIE", 2015, -1,
   "Moradores brancos resistem \xc3\xa0 integra\xc3\xa7\xc3\xa3o habitacional num conflito municipal racializado.",
   "Moradores brancos resistem \xc3\xa0 integra\xc3\xa7\xc3\xa3o habitacional num conflito municipal racializado. A refer\xc3\xaancia ajuda a compreender o combate ao preconceito e \xc3\xa0 discrimina\xc3\xa7\xc3\xa3o racial. N\xc3\xa3o demonstra todas as esp\xc3\xa9""cies de discrimina\xc3\xa7\xc3\xa3o enumeradas no dispositivo.",
   "o combate ao preconceito e \xc3\xa0 discrimina\xc3\xa7\xc3\xa3o racial", "Ilustra\xc3\xa7\xc3\xa3o de viola\xc3\xa7\xc3\xa3o", "EXP-SER-006"},
  {"CF88:ART.3:INC.IV|EXP-SER-007", "Pachinko", "S\xc3\x89RIE", 2022, 80,
   "A criadora descreve a experi\xc3\xaancia de uma fam\xc3\xadlia coreana zainichi, atravessada pela coloniza\xc3\xa7\xc3\xa3o, migra\xc3\xa7\xc3\xa3o e discrimina\xc3\xa7\xc3\xa3o no Jap\xc3\xa3o.",
   "A criadora descreve a experi\xc3\xaancia de uma fam\xc3\xadlia coreana zainichi, atravessada pela coloniza\xc3\xa7\xc3\xa3o, migra\xc3\xa7\xc3\xa3o e discrimina\xc3\xa7\xc3\xa3o no Jap\xc3\xa3o. A refer\xc3\xaancia ajuda a compreender o combate \xc3\xa0 discrimina\xc3\xa7\xc3\xa3o por origem \xc3\xa9tnica. N\xc3\xa3o demonstra todas as esp\xc3\xa9""cies de discrimina\xc3\xa7\xc3\xa3o enumeradas no dispositivo.",
   "o combate \xc3\xa0 discrimina\xc3\xa7\xc3\xa3o por origem \xc3\xa9tnica", "Ilustra\xc3\xa7\xc3\xa3o de viola\xc3\xa7\xc3\xa3o", "EXP-SER-007"},
  {"CF88:ART.3:INC.IV|REF-DOC-0002", "A 13\xc2\xaa Emenda", "DOCUMENT\xc3\x81RIO", 2016, 88,
   "O document\xc3\xa1rio examina a criminaliza\xc3\xa7\xc3\xa3o de afro-americanos e a expans\xc3\xa3o das pris\xc3\xb5""es.",
   "O document\xc3\xa1rio examina a criminaliza\xc3\xa7\xc3\xa3o de afro-americanos e a expans\xc3\xa3o das pris\xc3\xb5""es. A refer\xc3\xaancia ajuda a compreender o combate ao preconceito e \xc3\xa0 discrimina\xc3\xa7\xc3\xa3o racial. N\xc3\xa3o demonstra todas as esp\xc3\xa9""cies de discrimina\xc3\xa7\xc3\xa3o enumeradas no dispositivo.",
   "o combate ao preconceito e \xc3\xa0 discrimina\xc3\xa7\xc3\xa3o racial", "Ilustra\xc3\xa7\xc3\xa3o de viola\xc3\xa7\xc3\xa3o", "REF-DOC-0002"},
  {"CF88:ART.3:INC.IV|REF-LIV-0003", "O Sol \xc3\x89 para Todos", "LIVRO", 1960, 89,
   "Tom Robinson, homem negro falsamente acusado, \xc3\xa9 defendido por Atticus em um ambiente de preconceito racial e amea\xc3\xa7""a de linchamento.",
   "Tom Robinson, homem negro falsamente acusado, \xc3\xa9 defendido por Atticus em um ambiente de preconceito racial e amea\xc3\xa7""a de linchamento. A refer\xc3\xaancia ajuda a compreender o combate ao preconceito e \xc3\xa0 discrimina\xc3\xa7\xc3\xa3o racial. N\xc3\xa3o demonstra todas as esp\xc3\xa9""cies de discrimina\xc3\xa7\xc3\xa3o enumeradas no dispositivo.",
   "o combate ao preconceito e \xc3\xa0 discrimina\xc3\xa7\xc3\xa3o racial", "Ilustra\xc3\xa7\xc3\xa3o de viola\xc3\xa7\xc3\xa3o", "REF-LIV-0003"},
  {"CF88:ART.3:INC.IV|REF-LIV-0006", "A Revolu\xc3\xa7\xc3\xa3o dos Bichos", "LIVRO", 1945, 86,
   "A regra escrita passa a conceder igualdade maior a alguns animais; os porcos mant\xc3\xaam privil\xc3\xa9gios e os demais trabalham mais com ra\xc3\xa7\xc3\xb5""es inferiores.",
   "A regra escrita passa a conceder igualdade maior a alguns animais; os porcos mant\xc3\xaam privil\xc3\xa9gios e os demais trabalham mais com ra\xc3\xa7\xc3\xb5""es inferiores. A refer\xc3\xaancia ajuda a compreender o combate a distin\xc3\xa7\xc3\xb5""es arbitr\xc3\xa1rias no tratamento dos integrantes de uma comunidade. A distin\xc3\xa7\xc3\xa3o entre animais \xc3\xa9 aleg\xc3\xb3rica; n\xc3\xa3o \xc3\xa9 apresentada como discrimina\xc3\xa7\xc3\xa3o racial ou \xc3\xa9tnica humana.",
   "o combate a distin\xc3\xa7\xc3\xb5""es arbitr\xc3\xa1rias no tratamento dos integrantes de uma comunidade", "Analogia controlada", "REF-LIV-0006"},
  {"CF88:ART.43:CAPUT|EXP-LIV-003", "Forma\xc3\xa7\xc3\xa3o Econ\xc3\xb4mica do Brasil", "LIVRO", 1959, 86,
   "S\xc3\xadntese hist\xc3\xb3rico-estrutural da forma\xc3\xa7\xc3\xa3o econ\xc3\xb4mica brasileira, ciclos produtivos e desigualdades regionais.",
   "Furtado explica a forma\xc3\xa7\xc3\xa3o hist\xc3\xb3rica das desigualdades entre as regi\xc3\xb5""es brasileiras. O art. 43 autoriza a Uni\xc3\xa3o a articular sua a\xc3\xa7\xc3\xa3o em complexos regionais para reduzir essas desigualdades.",
   "Ajuda a compreender o problema que o art. 43 enfrenta e por que a Constitui\xc3\xa7\xc3\xa3o trata regi\xc3\xa3o como unidade de planejamento. N\xc3\xa3o descreve os instrumentos do \xc2\xa7 2\xc2\xba nem a organiza\xc3\xa7\xc3\xa3o dos \xc3\xb3rg\xc3\xa3os regionais.", "", "EXP-LIV-003 \xc2\xb7 REFERENCE_EXPANSION_01"},
  {"CF88:ART.43:PAR.2:INC.IV|EXP2-LIV-040", "Vidas Secas", "LIVRO", 1938, 84,
   "A seca, \xc3\xa1spera e cruel, impulsiona os personagens, retirantes em busca de meios de sobreviv\xc3\xaancia e de um futuro.",
   "O romance acompanha uma fam\xc3\xadlia de retirantes expulsa pela seca do sert\xc3\xa3o. O inciso IV escolhe exatamente esse cen\xc3\xa1rio como prioridade de incentivo regional.",
   "Facilita visualizar e lembrar o que s\xc3\xa3o \"regi\xc3\xb5""es de baixa renda sujeitas a secas peri\xc3\xb3""dicas\" e por que o aproveitamento da \xc3\xa1gua \xc3\xa9 prioridade. N\xc3\xa3o trata dos demais incentivos regionais.", "", "EXP2-LIV-040 \xc2\xb7 REFERENCE_EXPANSION_01"},
  {"CF88:ART.4:INC.VIII|EXP-DOC-009", "AmarElo \xe2\x80\x94 \xc3\x89 Tudo Pra Ontem", "DOCUMENT\xc3\x81RIO", 2020, 84,
   "Guilherme Wisnik analisa o document\xc3\xa1rio como den\xc3\xbancia do racismo estrutural brasileiro.",
   "Guilherme Wisnik analisa o document\xc3\xa1rio como den\xc3\xbancia do racismo estrutural brasileiro. A obra ajuda a compreender por que o racismo \xc3\xa9 objeto de rep\xc3\xba""dio constitucional. N\xc3\xa3o afirma terrorismo nem descreve integralmente a pol\xc3\xadtica externa brasileira.",
   "o rep\xc3\xba""dio ao racismo", "Contextualiza\xc3\xa7\xc3\xa3o hist\xc3\xb3rica", "EXP-DOC-009"},
  {"CF88:ART.4:INC.VIII|EXP-LIV-008", "A Cor da Lei", "LIVRO", 2017, -1,
   "Rothstein analisa como pol\xc3\xadticas federais, estaduais e locais produziram segrega\xc3\xa7\xc3\xa3o residencial.",
   "Rothstein analisa como pol\xc3\xadticas federais, estaduais e locais produziram segrega\xc3\xa7\xc3\xa3o residencial. A obra ajuda a compreender por que o racismo \xc3\xa9 objeto de rep\xc3\xba""dio constitucional. N\xc3\xa3o afirma terrorismo nem descreve integralmente a pol\xc3\xadtica externa brasileira.",
   "o rep\xc3\xba""dio ao racismo", "Contextualiza\xc3\xa7\xc3\xa3o hist\xc3\xb3rica", "EXP-LIV-008"},
  {"CF88:ART.4:INC.VIII|EXP-LIV-010", "Borderlands/La Frontera: The New Mestiza", "LIVRO", 1987, 80,
   "A resenha acad\xc3\xaamica relaciona a epistemologia de Borderlands \xc3\xa0 cr\xc3\xadtica da naturaliza\xc3\xa7\xc3\xa3o do racismo na vida americana.",
   "A resenha acad\xc3\xaamica relaciona a epistemologia de Borderlands \xc3\xa0 cr\xc3\xadtica da naturaliza\xc3\xa7\xc3\xa3o do racismo na vida americana. A obra ajuda a compreender por que o racismo \xc3\xa9 objeto de rep\xc3\xba""dio constitucional. N\xc3\xa3o afirma terrorismo nem descreve integralmente a pol\xc3\xadtica externa brasileira.",
   "o rep\xc3\xba""dio ao racismo", "Contextualiza\xc3\xa7\xc3\xa3o hist\xc3\xb3rica", "EXP-LIV-010"},
  {"CF88:ART.4:INC.VIII|EXP-SER-006", "Show Me a Hero", "S\xc3\x89RIE", 2015, -1,
   "Moradores brancos resistem \xc3\xa0 integra\xc3\xa7\xc3\xa3o habitacional num conflito municipal racializado.",
   "Moradores brancos resistem \xc3\xa0 integra\xc3\xa7\xc3\xa3o habitacional num conflito municipal racializado. A obra ajuda a compreender por que o racismo \xc3\xa9 objeto de rep\xc3\xba""dio constitucional. N\xc3\xa3o afirma terrorismo nem descreve integralmente a pol\xc3\xadtica externa brasileira.",
   "o rep\xc3\xba""dio ao racismo", "Ilustra\xc3\xa7\xc3\xa3o de viola\xc3\xa7\xc3\xa3o", "EXP-SER-006"},
  {"CF88:ART.4:INC.VIII|REF-DOC-0002", "A 13\xc2\xaa Emenda", "DOCUMENT\xc3\x81RIO", 2016, 88,
   "O document\xc3\xa1rio examina a criminaliza\xc3\xa7\xc3\xa3o de afro-americanos e a expans\xc3\xa3o das pris\xc3\xb5""es.",
   "O document\xc3\xa1rio examina a criminaliza\xc3\xa7\xc3\xa3o de afro-americanos e a expans\xc3\xa3o das pris\xc3\xb5""es. A obra ajuda a compreender por que o racismo \xc3\xa9 objeto de rep\xc3\xba""dio constitucional. N\xc3\xa3o afirma terrorismo nem descreve integralmente a pol\xc3\xadtica externa brasileira.",
   "o rep\xc3\xba""dio ao racismo", "Contextualiza\xc3\xa7\xc3\xa3o hist\xc3\xb3rica", "REF-DOC-0002"},
  {"CF88:ART.4:INC.VIII|REF-LIV-0003", "O Sol \xc3\x89 para Todos", "LIVRO", 1960, 89,
   "Tom Robinson, homem negro falsamente acusado, \xc3\xa9 defendido por Atticus em um ambiente de preconceito racial e amea\xc3\xa7""a de linchamento.",
   "Tom Robinson, homem negro falsamente acusado, \xc3\xa9 defendido por Atticus em um ambiente de preconceito racial e amea\xc3\xa7""a de linchamento. A obra ajuda a compreender por que o racismo \xc3\xa9 objeto de rep\xc3\xba""dio constitucional. N\xc3\xa3o afirma terrorismo nem descreve integralmente a pol\xc3\xadtica externa brasileira.",
   "o rep\xc3\xba""dio ao racismo", "Ilustra\xc3\xa7\xc3\xa3o de viola\xc3\xa7\xc3\xa3o", "REF-LIV-0003"},
  {"CF88:ART.52:INC.I|EXP-DOC-005", "O Processo", "DOCUMENT\xc3\x81RIO", 2018, 74,
   "Registro observacional dos bastidores do impeachment de Dilma Rousseff no Congresso e no Senado.",
   "O filme acompanha a defesa no processo de impeachment de 2016, incluindo a fase de julgamento no Senado.",
   "Ajuda a visualizar o Senado funcionando como \xc3\xb3rg\xc3\xa3o julgador. N\xc3\xa3o demonstra o qu\xc3\xb3rum e o rito completo previstos no par\xc3\xa1grafo \xc3\xbanico.\x0aLimites: Perspectiva de uma das partes; evitar leitura de m\xc3\xa9rito pol\xc3\xadtico.", "", "EXP-DOC-005 \xc2\xb7 REFERENCE_EXPANSION_01"},
  {"CF88:ART.58:PAR.3|EXP2-FIL-039", "Tropa de Elite 2: O Inimigo Agora \xc3\x89 Outro", "FILME", 2010, 76,
   "Nascimento passa \xc3\xa0 intelig\xc3\xaancia de seguran\xc3\xa7""a e enfrenta interesses de policiais e pol\xc3\xadticos corruptos beneficiados pelas a\xc3\xa7\xc3\xb5""es contra o tr\xc3\xa1""fico.",
   "Na trama, uma CPI da Assembleia Legislativa investiga mil\xc3\xad""cias ligadas a agentes p\xc3\xba""blicos e pol\xc3\xadticos.",
   "Facilita lembrar o que uma CPI faz (investigar fato determinado e remeter conclus\xc3\xb5""es ao Minist\xc3\xa9rio P\xc3\xba""blico). A CPI do filme \xc3\xa9 estadual e ficcionalizada; n\xc3\xa3o mostra os limites jur\xc3\xad""dicos (reserva de jurisdi\xc3\xa7\xc3\xa3o).\x0aLimites: CPI estadual em obra de fic\xc3\xa7\xc3\xa3o; viol\xc3\xaancia expl\xc3\xad""cita.", "", "EXP2-FIL-039 \xc2\xb7 REFERENCE_EXPANSION_01"},
  {"CF88:ART.5:CAPUT|REF-FIL-0004", "Filad\xc3\xa9lfia", "FILME", 1993, -1,
   "Advogados movem a\xc3\xa7\xc3\xa3o contra escrit\xc3\xb3rio por discrimina\xc3\xa7\xc3\xa3o ligada \xc3\xa0 AIDS no ambiente de trabalho.",
   "Advogados movem a\xc3\xa7\xc3\xa3o contra escrit\xc3\xb3rio por discrimina\xc3\xa7\xc3\xa3o ligada \xc3\xa0 AIDS no ambiente de trabalho. A refer\xc3\xaancia ajuda a compreender a igualdade de tratamento, sem distin\xc3\xa7\xc3\xb5""es arbitr\xc3\xa1rias. N\xc3\xa3o demonstra todas as garantias e condi\xc3\xa7\xc3\xb5""es enumeradas no art. 5\xc2\xba.",
   "a igualdade de tratamento, sem distin\xc3\xa7\xc3\xb5""es arbitr\xc3\xa1rias", "Ilustra\xc3\xa7\xc3\xa3o de viola\xc3\xa7\xc3\xa3o", "REF-FIL-0004"},
  {"CF88:ART.5:CAPUT|REF-LIV-0006", "A Revolu\xc3\xa7\xc3\xa3o dos Bichos", "LIVRO", 1945, 57,
   "A regra escrita passa a conceder igualdade maior a alguns animais; os porcos mant\xc3\xaam privil\xc3\xa9gios e os demais trabalham mais com ra\xc3\xa7\xc3\xb5""es inferiores.",
   "A regra escrita passa a conceder igualdade maior a alguns animais; os porcos mant\xc3\xaam privil\xc3\xa9gios e os demais trabalham mais com ra\xc3\xa7\xc3\xb5""es inferiores. A refer\xc3\xaancia ajuda a compreender a igualdade de tratamento, sem distin\xc3\xa7\xc3\xb5""es arbitr\xc3\xa1rias. N\xc3\xa3o demonstra todas as garantias e condi\xc3\xa7\xc3\xb5""es enumeradas no art. 5\xc2\xba.",
   "a igualdade de tratamento, sem distin\xc3\xa7\xc3\xb5""es arbitr\xc3\xa1rias", "Analogia controlada", "REF-LIV-0006"},
  {"CF88:ART.5:INC.III|REF-LIV-0005", "Vigiar e Punir", "LIVRO", 1975, 79,
   "Foucault argumenta que a aboli\xc3\xa7\xc3\xa3o da tortura e a penitenci\xc3\xa1ria moderna deslocaram o foco do castigo do corpo para a subjetividade do preso.",
   "Foucault argumenta que a aboli\xc3\xa7\xc3\xa3o da tortura e a penitenci\xc3\xa1ria moderna deslocaram o foco do castigo do corpo para a subjetividade do preso. A refer\xc3\xaancia ajuda a compreender a proibi\xc3\xa7\xc3\xa3o da tortura. A rela\xc3\xa7\xc3\xa3o se limita \xc3\xa0 an\xc3\xa1lise hist\xc3\xb3rica da puni\xc3\xa7\xc3\xa3o; n\xc3\xa3o abrange todas as formas de tratamento desumano ou degradante.",
   "a proibi\xc3\xa7\xc3\xa3o da tortura", "Contextualiza\xc3\xa7\xc3\xa3o hist\xc3\xb3rica", "REF-LIV-0005"},
  {"CF88:ART.5:INC.IV|REF-FIL-0002", "V de Vingan\xc3\xa7""a", "FILME", 2005, 87,
   "As notas de produ\xc3\xa7\xc3\xa3o do filme descrevem a morte dos pais de Evey por se manifestarem contra o regime repressivo.",
   "As notas de produ\xc3\xa7\xc3\xa3o do filme descrevem a morte dos pais de Evey por se manifestarem contra o regime repressivo. A refer\xc3\xaancia ajuda a compreender a liberdade de manifesta\xc3\xa7\xc3\xa3o do pensamento. N\xc3\xa3o demonstra a regra constitucional de veda\xc3\xa7\xc3\xa3o ao anonimato.",
   "a liberdade de manifesta\xc3\xa7\xc3\xa3o do pensamento", "Ilustra\xc3\xa7\xc3\xa3o de viola\xc3\xa7\xc3\xa3o", "REF-FIL-0002"},
  {"CF88:ART.5:INC.IV|REF-FIL-0006", "The Post: A Guerra Secreta", "FILME", 2017, 85,
   "A administra\xc3\xa7\xc3\xa3o Nixon tenta restringir a divulga\xc3\xa7\xc3\xa3o jornal\xc3\xadstica dos Pentagon Papers; os editores enfrentam a medida para publicar informa\xc3\xa7\xc3\xb5""es cr\xc3\xadticas ao governo.",
   "A administra\xc3\xa7\xc3\xa3o Nixon tenta restringir a divulga\xc3\xa7\xc3\xa3o jornal\xc3\xadstica dos Pentagon Papers; os editores enfrentam a medida para publicar informa\xc3\xa7\xc3\xb5""es cr\xc3\xadticas ao governo. A refer\xc3\xaancia ajuda a compreender a liberdade de manifesta\xc3\xa7\xc3\xa3o do pensamento. N\xc3\xa3o demonstra a regra constitucional de veda\xc3\xa7\xc3\xa3o ao anonimato.",
   "a liberdade de manifesta\xc3\xa7\xc3\xa3o do pensamento", "Ilustra\xc3\xa7\xc3\xa3o de viola\xc3\xa7\xc3\xa3o", "REF-FIL-0006"},
  {"CF88:ART.5:INC.IV|REF-LIV-0001", "1984", "LIVRO", 1949, 78,
   "O Partido pro\xc3\xad""be express\xc3\xa3o dissidente; Winston registra pensamentos e discute sua derrubada, sendo capturado e reeducado pela Pol\xc3\xad""cia do Pensamento.",
   "O Partido pro\xc3\xad""be express\xc3\xa3o dissidente; Winston registra pensamentos e discute sua derrubada, sendo capturado e reeducado pela Pol\xc3\xad""cia do Pensamento. A refer\xc3\xaancia ajuda a compreender a liberdade de manifesta\xc3\xa7\xc3\xa3o do pensamento. N\xc3\xa3o demonstra a regra constitucional de veda\xc3\xa7\xc3\xa3o ao anonimato.",
   "a liberdade de manifesta\xc3\xa7\xc3\xa3o do pensamento", "Ilustra\xc3\xa7\xc3\xa3o de viola\xc3\xa7\xc3\xa3o", "REF-LIV-0001"},
  {"CF88:ART.5:INC.IX|REF-FIL-0006", "The Post: A Guerra Secreta", "FILME", 2017, 92,
   "A administra\xc3\xa7\xc3\xa3o Nixon tenta restringir a divulga\xc3\xa7\xc3\xa3o jornal\xc3\xadstica dos Pentagon Papers; os editores enfrentam a medida para publicar informa\xc3\xa7\xc3\xb5""es cr\xc3\xadticas ao governo.\x0a""Editora e editor do Washington Post exp\xc3\xb5""em segredos governamentais por meio dos Pentagon Papers, arriscando carreira e liberdade.",
   "A administra\xc3\xa7\xc3\xa3o Nixon tenta restringir a divulga\xc3\xa7\xc3\xa3o jornal\xc3\xadstica dos Pentagon Papers; os editores enfrentam a medida para publicar informa\xc3\xa7\xc3\xb5""es cr\xc3\xadticas ao governo. A refer\xc3\xaancia ajuda a compreender a liberdade de comunica\xc3\xa7\xc3\xa3o jornal\xc3\xadstica sem censura. N\xc3\xa3o afirma exerc\xc3\xad""cio de todas as modalidades de atividade art\xc3\xadstica, cient\xc3\xad""fica e intelectual nem regime de licenciamento.\x0a""Editora e editor do Washington Post exp\xc3\xb5""em segredos governamentais por meio dos Pentagon Papers, arriscando carreira e liberdade. A refer\xc3\xaancia ajuda a compreender a liberdade de comunica\xc3\xa7\xc3\xa3o jornal\xc3\xadstica sem censura. N\xc3\xa3o afirma exerc\xc3\xad""cio de todas as modalidades de atividade art\xc3\xadstica, cient\xc3\xad""fica e intelectual nem regime de licenciamento.",
   "a liberdade de comunica\xc3\xa7\xc3\xa3o jornal\xc3\xadstica sem censura", "Ilustra\xc3\xa7\xc3\xa3o de viola\xc3\xa7\xc3\xa3o", "REF-FIL-0006"},
  {"CF88:ART.5:INC.IX|REF-LIV-0001", "1984", "LIVRO", 1949, 83,
   "O Partido pro\xc3\xad""be express\xc3\xa3o dissidente; Winston registra pensamentos e discute sua derrubada, sendo capturado e reeducado pela Pol\xc3\xad""cia do Pensamento.",
   "O Partido pro\xc3\xad""be express\xc3\xa3o dissidente; Winston registra pensamentos e discute sua derrubada, sendo capturado e reeducado pela Pol\xc3\xad""cia do Pensamento. A refer\xc3\xaancia ajuda a compreender a liberdade de express\xc3\xa3o intelectual diante da repress\xc3\xa3o a pensamentos e escritos dissidentes. N\xc3\xa3o demonstra atividade art\xc3\xadstica ou cient\xc3\xad""fica espec\xc3\xad""fica nem todas as modalidades de comunica\xc3\xa7\xc3\xa3o.",
   "a liberdade de express\xc3\xa3o intelectual diante da repress\xc3\xa3o a pensamentos e escritos dissidentes", "Ilustra\xc3\xa7\xc3\xa3o de viola\xc3\xa7\xc3\xa3o", "REF-LIV-0001"},
  {"CF88:ART.5:INC.I|REF-SER-0002", "The Handmaid's Tale", "S\xc3\x89RIE", 2017, 92,
   "Mulheres f\xc3\xa9rteis s\xc3\xa3o submetidas \xc3\xa0 servid\xc3\xa3o reprodutiva em Gilead.",
   "Mulheres f\xc3\xa9rteis s\xc3\xa3o submetidas \xc3\xa0 servid\xc3\xa3o reprodutiva em Gilead. A refer\xc3\xaancia ajuda a compreender a igualdade de direitos entre homens e mulheres. N\xc3\xa3o representa todos os direitos e obriga\xc3\xa7\xc3\xb5""es constitucionais relativos \xc3\xa0 igualdade de g\xc3\xaanero.",
   "a igualdade de direitos entre homens e mulheres", "Ilustra\xc3\xa7\xc3\xa3o de viola\xc3\xa7\xc3\xa3o", "REF-SER-0002"},
  {"CF88:ART.5:INC.LIV|REF-FIL-0001", "12 Homens e uma Senten\xc3\xa7""a", "FILME", 1957, 92,
   "Um jurado com d\xc3\xbavida razo\xc3\xa1vel examina novamente os objetos de prova e depoimentos; os demais reconsideram a culpa do acusado.",
   "Um jurado com d\xc3\xbavida razo\xc3\xa1vel examina novamente os objetos de prova e depoimentos; os demais reconsideram a culpa do acusado. A refer\xc3\xaancia ajuda a compreender a prote\xc3\xa7\xc3\xa3o contra a priva\xc3\xa7\xc3\xa3o arbitr\xc3\xa1ria de liberdade e a exig\xc3\xaancia de um processo justo. N\xc3\xa3o prova o cumprimento ou a viola\xc3\xa7\xc3\xa3o de cada etapa do devido processo legal brasileiro.",
   "a prote\xc3\xa7\xc3\xa3o contra a priva\xc3\xa7\xc3\xa3o arbitr\xc3\xa1ria de liberdade e a exig\xc3\xaancia de um processo justo", "Analogia controlada", "REF-FIL-0001"},
  {"CF88:ART.5:INC.LIV|REF-LIV-0002", "O Processo", "LIVRO", 1925, 92,
   "Josef K. enfrenta uma persecu\xc3\xa7\xc3\xa3o sem conhecer a natureza da acusa\xc3\xa7\xc3\xa3o.",
   "Josef K. enfrenta uma persecu\xc3\xa7\xc3\xa3o sem conhecer a natureza da acusa\xc3\xa7\xc3\xa3o. A refer\xc3\xaancia ajuda a compreender a prote\xc3\xa7\xc3\xa3o contra a priva\xc3\xa7\xc3\xa3o arbitr\xc3\xa1ria de liberdade e a exig\xc3\xaancia de um processo justo. N\xc3\xa3o prova o cumprimento ou a viola\xc3\xa7\xc3\xa3o de cada etapa do devido processo legal brasileiro.",
   "a prote\xc3\xa7\xc3\xa3o contra a priva\xc3\xa7\xc3\xa3o arbitr\xc3\xa1ria de liberdade e a exig\xc3\xaancia de um processo justo", "Ilustra\xc3\xa7\xc3\xa3o de viola\xc3\xa7\xc3\xa3o", "REF-LIV-0002"},
  {"CF88:ART.5:INC.LIV|REF-SER-0001", "Olhos que Condenam", "S\xc3\x89RIE", 2019, 92,
   "Cinco adolescentes s\xc3\xa3o detidos e coagidos a confessar um ataque que n\xc3\xa3o cometeram.",
   "Cinco adolescentes s\xc3\xa3o detidos e coagidos a confessar um ataque que n\xc3\xa3o cometeram. A refer\xc3\xaancia ajuda a compreender a prote\xc3\xa7\xc3\xa3o contra a priva\xc3\xa7\xc3\xa3o arbitr\xc3\xa1ria de liberdade e a exig\xc3\xaancia de um processo justo. N\xc3\xa3o prova o cumprimento ou a viola\xc3\xa7\xc3\xa3o de cada etapa do devido processo legal brasileiro.",
   "a prote\xc3\xa7\xc3\xa3o contra a priva\xc3\xa7\xc3\xa3o arbitr\xc3\xa1ria de liberdade e a exig\xc3\xaancia de um processo justo", "Ilustra\xc3\xa7\xc3\xa3o de viola\xc3\xa7\xc3\xa3o", "REF-SER-0001"},
  {"CF88:ART.5:INC.LVII|REF-FIL-0001", "12 Homens e uma Senten\xc3\xa7""a", "FILME", 1957, 85,
   "Um jurado com d\xc3\xbavida razo\xc3\xa1vel examina novamente os objetos de prova e depoimentos; os demais reconsideram a culpa do acusado.",
   "Um jurado com d\xc3\xbavida razo\xc3\xa1vel examina novamente os objetos de prova e depoimentos; os demais reconsideram a culpa do acusado. A refer\xc3\xaancia ajuda a compreender a cautela em atribuir culpa ao acusado diante de d\xc3\xbavida probat\xc3\xb3ria. A compara\xc3\xa7\xc3\xa3o \xc3\xa9 pedag\xc3\xb3gica; n\xc3\xa3o reproduz a estrutura recursal nem demonstra o tr\xc3\xa2nsito em julgado brasileiro.",
   "a cautela em atribuir culpa ao acusado diante de d\xc3\xbavida probat\xc3\xb3ria", "Analogia controlada", "REF-FIL-0001"},
  {"CF88:ART.5:INC.LV|REF-LIV-0002", "O Processo", "LIVRO", 1925, 88,
   "Josef K. enfrenta uma persecu\xc3\xa7\xc3\xa3o sem conhecer a natureza da acusa\xc3\xa7\xc3\xa3o.",
   "Josef K. enfrenta uma persecu\xc3\xa7\xc3\xa3o sem conhecer a natureza da acusa\xc3\xa7\xc3\xa3o. A refer\xc3\xaancia ajuda a compreender a possibilidade de conhecer a acusa\xc3\xa7\xc3\xa3o e exercer defesa efetiva. N\xc3\xa3o representa todos os meios e recursos do contradit\xc3\xb3rio e da ampla defesa no sistema brasileiro.",
   "a possibilidade de conhecer a acusa\xc3\xa7\xc3\xa3o e exercer defesa efetiva", "Ilustra\xc3\xa7\xc3\xa3o de viola\xc3\xa7\xc3\xa3o", "REF-LIV-0002"},
  {"CF88:ART.5:INC.LXXIX|REF-DOC-0001", "Privacidade Hackeada", "DOCUMENT\xc3\x81RIO", 2019, 91,
   "O document\xc3\xa1rio examina a explora\xc3\xa7\xc3\xa3o de dados pessoais no esc\xc3\xa2ndalo Cambridge Analytica/Facebook e a disputa pelo controle de informa\xc3\xa7\xc3\xb5""es \xc3\xadntimas.",
   "O document\xc3\xa1rio examina a explora\xc3\xa7\xc3\xa3o de dados pessoais no esc\xc3\xa2ndalo Cambridge Analytica/Facebook e a disputa pelo controle de informa\xc3\xa7\xc3\xb5""es \xc3\xadntimas. A refer\xc3\xaancia ajuda a compreender a prote\xc3\xa7\xc3\xa3o dos dados pessoais contra usos invasivos ou abusivos. N\xc3\xa3o demonstra todo o regime legal de tratamento de dados nem depende de que a informa\xc3\xa7\xc3\xa3o esteja em meio digital.",
   "a prote\xc3\xa7\xc3\xa3o dos dados pessoais contra usos invasivos ou abusivos", "Ilustra\xc3\xa7\xc3\xa3o de viola\xc3\xa7\xc3\xa3o", "REF-DOC-0001"},
  {"CF88:ART.5:INC.LXXIX|REF-FIL-0003", "A Vida dos Outros", "FILME", 2006, 91,
   "Hempf usa informa\xc3\xa7\xc3\xa3o sobre a depend\xc3\xaancia qu\xc3\xadmica de Christa-Maria para for\xc3\xa7\xc3\xa1-la a revelar a autoria do artigo.",
   "Hempf usa informa\xc3\xa7\xc3\xa3o sobre a depend\xc3\xaancia qu\xc3\xadmica de Christa-Maria para for\xc3\xa7\xc3\xa1-la a revelar a autoria do artigo. A refer\xc3\xaancia ajuda a compreender a prote\xc3\xa7\xc3\xa3o dos dados pessoais contra usos invasivos ou abusivos. N\xc3\xa3o demonstra todo o regime legal de tratamento de dados nem depende de que a informa\xc3\xa7\xc3\xa3o esteja em meio digital.",
   "a prote\xc3\xa7\xc3\xa3o dos dados pessoais contra usos invasivos ou abusivos", "Ilustra\xc3\xa7\xc3\xa3o de viola\xc3\xa7\xc3\xa3o", "REF-FIL-0003"},
  {"CF88:ART.5:INC.VIII|EXP-FIL-009", "Timbuktu", "FILME", 2014, 90,
   "Autoridades fundamentalistas restringem costumes e a vida dos moradores impondo sua interpreta\xc3\xa7\xc3\xa3o religiosa.",
   "Autoridades fundamentalistas restringem costumes e a vida dos moradores impondo sua interpreta\xc3\xa7\xc3\xa3o religiosa. A refer\xc3\xaancia ajuda a compreender a prote\xc3\xa7\xc3\xa3o contra a priva\xc3\xa7\xc3\xa3o de direitos por motivo de cren\xc3\xa7""a. N\xc3\xa3o afirma recusa de obriga\xc3\xa7\xc3\xa3o legal geral nem de presta\xc3\xa7\xc3\xa3o alternativa fixada em lei.",
   "a prote\xc3\xa7\xc3\xa3o contra a priva\xc3\xa7\xc3\xa3o de direitos por motivo de cren\xc3\xa7""a", "Ilustra\xc3\xa7\xc3\xa3o de viola\xc3\xa7\xc3\xa3o", "EXP-FIL-009"},
  {"CF88:ART.5:INC.VI|EXP-FIL-009", "Timbuktu", "FILME", 2014, 88,
   "Fundamentalistas imp\xc3\xb5""em terror e regras para suprimir uma pr\xc3\xa1tica aberta e tolerante do Isl\xc3\xa3.",
   "Fundamentalistas imp\xc3\xb5""em terror e regras para suprimir uma pr\xc3\xa1tica aberta e tolerante do Isl\xc3\xa3. A refer\xc3\xaancia ajuda a compreender a liberdade de cren\xc3\xa7""a e de pr\xc3\xa1tica religiosa. N\xc3\xa3o demonstra todas as garantias legais de locais de culto e liturgias.",
   "a liberdade de cren\xc3\xa7""a e de pr\xc3\xa1tica religiosa", "Ilustra\xc3\xa7\xc3\xa3o de viola\xc3\xa7\xc3\xa3o", "EXP-FIL-009"},
  {"CF88:ART.5:INC.XIII|REF-FIL-0004", "Filad\xc3\xa9lfia", "FILME", 1993, 79,
   "Advogados movem a\xc3\xa7\xc3\xa3o contra escrit\xc3\xb3rio por discrimina\xc3\xa7\xc3\xa3o ligada \xc3\xa0 AIDS no ambiente de trabalho.",
   "Advogados movem a\xc3\xa7\xc3\xa3o contra escrit\xc3\xb3rio por discrimina\xc3\xa7\xc3\xa3o ligada \xc3\xa0 AIDS no ambiente de trabalho. A refer\xc3\xaancia ajuda a compreender a liberdade de exercer uma profiss\xc3\xa3o sem discrimina\xc3\xa7\xc3\xa3o. N\xc3\xa3o afirma cumprimento, dispensa ou viola\xc3\xa7\xc3\xa3o das qualifica\xc3\xa7\xc3\xb5""es profissionais que a lei estabelecer.",
   "a liberdade de exercer uma profiss\xc3\xa3o sem discrimina\xc3\xa7\xc3\xa3o", "Ilustra\xc3\xa7\xc3\xa3o de viola\xc3\xa7\xc3\xa3o", "REF-FIL-0004"},
  {"CF88:ART.5:INC.XII|REF-FIL-0003", "A Vida dos Outros", "FILME", 2006, 89,
   "A Stasi instala escutas no apartamento do dramaturgo, monitoradas a partir do s\xc3\xb3t\xc3\xa3o por Wiesler.",
   "A Stasi instala escutas no apartamento do dramaturgo, monitoradas a partir do s\xc3\xb3t\xc3\xa3o por Wiesler. A refer\xc3\xaancia ajuda a compreender o sigilo das comunica\xc3\xa7\xc3\xb5""es privadas diante de escutas. N\xc3\xa3o demonstra todos os meios de comunica\xc3\xa7\xc3\xa3o enumerados nem as condi\xc3\xa7\xc3\xb5""es brasileiras de autoriza\xc3\xa7\xc3\xa3o judicial de intercepta\xc3\xa7\xc3\xa3o.",
   "o sigilo das comunica\xc3\xa7\xc3\xb5""es privadas diante de escutas", "Ilustra\xc3\xa7\xc3\xa3o de viola\xc3\xa7\xc3\xa3o", "REF-FIL-0003"},
  {"CF88:ART.5:INC.XIV|REF-SER-0003", "Chernobyl", "S\xc3\x89RIE", 2019, 82,
   "A miniss\xc3\xa9rie retrata desinforma\xc3\xa7\xc3\xa3o; Khomyuk encontra obst\xc3\xa1""culos governamentais para esclarecer o acidente, e os protagonistas arriscam-se para expor a verdade.",
   "A miniss\xc3\xa9rie retrata desinforma\xc3\xa7\xc3\xa3o; Khomyuk encontra obst\xc3\xa1""culos governamentais para esclarecer o acidente, e os protagonistas arriscam-se para expor a verdade. A refer\xc3\xaancia ajuda a compreender o acesso \xc3\xa0 informa\xc3\xa7\xc3\xa3o diante de sua oculta\xc3\xa7\xc3\xa3o por autoridades. N\xc3\xa3o afirma sigilo da fonte no exerc\xc3\xad""cio profissional.",
   "o acesso \xc3\xa0 informa\xc3\xa7\xc3\xa3o diante de sua oculta\xc3\xa7\xc3\xa3o por autoridades", "Ilustra\xc3\xa7\xc3\xa3o de viola\xc3\xa7\xc3\xa3o", "REF-SER-0003"},
  {"CF88:ART.5:INC.XLII|EXP-DOC-009", "AmarElo \xe2\x80\x94 \xc3\x89 Tudo Pra Ontem", "DOCUMENT\xc3\x81RIO", 2020, 84,
   "Guilherme Wisnik analisa o document\xc3\xa1rio como den\xc3\xbancia do racismo estrutural brasileiro.",
   "Guilherme Wisnik analisa o document\xc3\xa1rio como den\xc3\xbancia do racismo estrutural brasileiro. Essa an\xc3\xa1lise contextualiza o racismo, problema social que a Constitui\xc3\xa7\xc3\xa3o trata como crime. A contextualiza\xc3\xa7\xc3\xa3o n\xc3\xa3o demonstra o regime brasileiro de inafian\xc3\xa7""abilidade, imprescritibilidade ou aplica\xc3\xa7\xc3\xa3o da pena de reclus\xc3\xa3o.",
   "o contexto social e hist\xc3\xb3rico do racismo que a Constitui\xc3\xa7\xc3\xa3o criminaliza", "Contextualiza\xc3\xa7\xc3\xa3o hist\xc3\xb3rica", "EXP-DOC-009"},
  {"CF88:ART.5:INC.XLII|EXP-LIV-008", "A Cor da Lei", "LIVRO", 2017, -1,
   "Rothstein analisa como pol\xc3\xadticas federais, estaduais e locais produziram segrega\xc3\xa7\xc3\xa3o residencial.",
   "Rothstein analisa como pol\xc3\xadticas federais, estaduais e locais produziram segrega\xc3\xa7\xc3\xa3o residencial. Essa an\xc3\xa1lise contextualiza o racismo, problema social que a Constitui\xc3\xa7\xc3\xa3o trata como crime. A contextualiza\xc3\xa7\xc3\xa3o n\xc3\xa3o demonstra o regime brasileiro de inafian\xc3\xa7""abilidade, imprescritibilidade ou aplica\xc3\xa7\xc3\xa3o da pena de reclus\xc3\xa3o.",
   "o contexto social e hist\xc3\xb3rico do racismo que a Constitui\xc3\xa7\xc3\xa3o criminaliza", "Contextualiza\xc3\xa7\xc3\xa3o hist\xc3\xb3rica", "EXP-LIV-008"},
  {"CF88:ART.5:INC.XLII|EXP-LIV-010", "Borderlands/La Frontera: The New Mestiza", "LIVRO", 1987, 80,
   "A resenha acad\xc3\xaamica relaciona a epistemologia de Borderlands \xc3\xa0 cr\xc3\xadtica da naturaliza\xc3\xa7\xc3\xa3o do racismo na vida americana.",
   "A resenha acad\xc3\xaamica relaciona a epistemologia de Borderlands \xc3\xa0 cr\xc3\xadtica da naturaliza\xc3\xa7\xc3\xa3o do racismo na vida americana. Essa an\xc3\xa1lise contextualiza o racismo, problema social que a Constitui\xc3\xa7\xc3\xa3o trata como crime. A contextualiza\xc3\xa7\xc3\xa3o n\xc3\xa3o demonstra o regime brasileiro de inafian\xc3\xa7""abilidade, imprescritibilidade ou aplica\xc3\xa7\xc3\xa3o da pena de reclus\xc3\xa3o.",
   "o contexto social e hist\xc3\xb3rico do racismo que a Constitui\xc3\xa7\xc3\xa3o criminaliza", "Contextualiza\xc3\xa7\xc3\xa3o hist\xc3\xb3rica", "EXP-LIV-010"},
  {"CF88:ART.5:INC.XLII|REF-DOC-0002", "A 13\xc2\xaa Emenda", "DOCUMENT\xc3\x81RIO", 2016, 88,
   "O document\xc3\xa1rio examina a criminaliza\xc3\xa7\xc3\xa3o de afro-americanos e a expans\xc3\xa3o das pris\xc3\xb5""es.",
   "O document\xc3\xa1rio examina a criminaliza\xc3\xa7\xc3\xa3o de afro-americanos e a expans\xc3\xa3o das pris\xc3\xb5""es. Essa an\xc3\xa1lise contextualiza o racismo, problema social que a Constitui\xc3\xa7\xc3\xa3o trata como crime. A contextualiza\xc3\xa7\xc3\xa3o n\xc3\xa3o demonstra o regime brasileiro de inafian\xc3\xa7""abilidade, imprescritibilidade ou aplica\xc3\xa7\xc3\xa3o da pena de reclus\xc3\xa3o.",
   "o contexto social e hist\xc3\xb3rico do racismo que a Constitui\xc3\xa7\xc3\xa3o criminaliza", "Contextualiza\xc3\xa7\xc3\xa3o hist\xc3\xb3rica", "REF-DOC-0002"},
  {"CF88:ART.5:INC.XLIX|REF-DOC-0002", "A 13\xc2\xaa Emenda", "DOCUMENT\xc3\x81RIO", 2016, 70,
   "O document\xc3\xa1rio inclui o testemunho de Kalief Browder, submetido a condi\xc3\xa7\xc3\xb5""es prisionais extremamente brutais durante tr\xc3\xaas anos.",
   "O document\xc3\xa1rio inclui o testemunho de Kalief Browder, submetido a condi\xc3\xa7\xc3\xb5""es prisionais extremamente brutais durante tr\xc3\xaas anos. A refer\xc3\xaancia ajuda a compreender o respeito \xc3\xa0 integridade f\xc3\xadsica e moral da pessoa presa. N\xc3\xa3o descreve integralmente o regime penitenci\xc3\xa1rio brasileiro.",
   "o respeito \xc3\xa0 integridade f\xc3\xadsica e moral da pessoa presa", "Ilustra\xc3\xa7\xc3\xa3o de viola\xc3\xa7\xc3\xa3o", "REF-DOC-0002"},
  {"CF88:ART.5:INC.XLIX|REF-SER-0001", "Olhos que Condenam", "S\xc3\x89RIE", 2019, 65,
   "A s\xc3\xa9rie mostra Korey sofrendo viol\xc3\xaancia f\xc3\xadsica na pris\xc3\xa3o; o isolamento afasta agress\xc3\xb5""es, mas agrava sofrimento ps\xc3\xadquico.",
   "A s\xc3\xa9rie mostra Korey sofrendo viol\xc3\xaancia f\xc3\xadsica na pris\xc3\xa3o; o isolamento afasta agress\xc3\xb5""es, mas agrava sofrimento ps\xc3\xadquico. A refer\xc3\xaancia ajuda a compreender o respeito \xc3\xa0 integridade f\xc3\xadsica e moral da pessoa presa. N\xc3\xa3o descreve integralmente o regime penitenci\xc3\xa1rio brasileiro.",
   "o respeito \xc3\xa0 integridade f\xc3\xadsica e moral da pessoa presa", "Ilustra\xc3\xa7\xc3\xa3o de viola\xc3\xa7\xc3\xa3o", "REF-SER-0001"},
  {"CF88:ART.5:INC.XV|REF-JOG-0001", "Papers, Please", "JOGO", 2013, 38,
   "O jogador inspeciona documentos, busca e impress\xc3\xb5""es digitais para decidir quem entra, \xc3\xa9 recusado ou preso na fronteira de Arstotzka.",
   "O jogador inspeciona documentos, busca e impress\xc3\xb5""es digitais para decidir quem entra, \xc3\xa9 recusado ou preso na fronteira de Arstotzka. A refer\xc3\xaancia ajuda a compreender a liberdade de circula\xc3\xa7\xc3\xa3o e de ingresso no territ\xc3\xb3rio. A fronteira fict\xc3\xad""cia permite compara\xc3\xa7\xc3\xa3o; n\xc3\xa3o comprova os requisitos brasileiros de ingresso, perman\xc3\xaancia, sa\xc3\xad""da ou circula\xc3\xa7\xc3\xa3o de bens.",
   "a liberdade de circula\xc3\xa7\xc3\xa3o e de ingresso no territ\xc3\xb3rio", "Analogia controlada", "REF-JOG-0001"},
  {"CF88:ART.5:INC.XXII|EXP-FIL-005", "Leviat\xc3\xa3", "FILME", 2014, 66,
   "Um prefeito corrupto tenta tomar o neg\xc3\xb3""cio, a casa e o terreno de Kolya, que recorre a um advogado.",
   "Um prefeito corrupto tenta tomar o neg\xc3\xb3""cio, a casa e o terreno de Kolya, que recorre a um advogado. A refer\xc3\xaancia ajuda a compreender a prote\xc3\xa7\xc3\xa3o do direito de propriedade. N\xc3\xa3o demonstra todos os limites constitucionais da propriedade nem o regime brasileiro de desapropria\xc3\xa7\xc3\xa3o.",
   "a prote\xc3\xa7\xc3\xa3o do direito de propriedade", "Ilustra\xc3\xa7\xc3\xa3o de viola\xc3\xa7\xc3\xa3o", "EXP-FIL-005"},
  {"CF88:ART.5:INC.XXXV|REF-FIL-0007", "O Pre\xc3\xa7o da Verdade", "FILME", 2019, 74,
   "Bilott trava uma disputa jur\xc3\xad""dica contra a DuPont por efeitos de toxinas PFOA.",
   "Bilott trava uma disputa jur\xc3\xad""dica contra a DuPont por efeitos de toxinas PFOA. A refer\xc3\xaancia ajuda a compreender o acesso \xc3\xa0 Justi\xc3\xa7""a para buscar prote\xc3\xa7\xc3\xa3o diante de les\xc3\xa3o ou amea\xc3\xa7""a a direito. N\xc3\xa3o demonstra a exist\xc3\xaancia de lei brasileira que exclua a aprecia\xc3\xa7\xc3\xa3o judicial.",
   "o acesso \xc3\xa0 Justi\xc3\xa7""a para buscar prote\xc3\xa7\xc3\xa3o diante de les\xc3\xa3o ou amea\xc3\xa7""a a direito", "Analogia controlada", "REF-FIL-0007"},
  {"CF88:ART.5:INC.X|REF-DOC-0001", "Privacidade Hackeada", "DOCUMENT\xc3\x81RIO", 2019, 91,
   "O document\xc3\xa1rio examina a explora\xc3\xa7\xc3\xa3o de dados pessoais no esc\xc3\xa2ndalo Cambridge Analytica/Facebook e a disputa pelo controle de informa\xc3\xa7\xc3\xb5""es \xc3\xadntimas.",
   "O document\xc3\xa1rio examina a explora\xc3\xa7\xc3\xa3o de dados pessoais no esc\xc3\xa2ndalo Cambridge Analytica/Facebook e a disputa pelo controle de informa\xc3\xa7\xc3\xb5""es \xc3\xadntimas. A refer\xc3\xaancia ajuda a compreender a prote\xc3\xa7\xc3\xa3o da intimidade e da vida privada. N\xc3\xa3o demonstra, por si, viola\xc3\xa7\xc3\xa3o da honra ou da imagem nem indeniza\xc3\xa7\xc3\xa3o por dano material ou moral.",
   "a prote\xc3\xa7\xc3\xa3o da intimidade e da vida privada", "Ilustra\xc3\xa7\xc3\xa3o de viola\xc3\xa7\xc3\xa3o", "REF-DOC-0001"},
  {"CF88:ART.5:INC.X|REF-FIL-0003", "A Vida dos Outros", "FILME", 2006, 91,
   "Hempf usa informa\xc3\xa7\xc3\xa3o sobre a depend\xc3\xaancia qu\xc3\xadmica de Christa-Maria para for\xc3\xa7\xc3\xa1-la a revelar a autoria do artigo.\x0a""A Stasi instala escutas no apartamento do dramaturgo, monitoradas a partir do s\xc3\xb3t\xc3\xa3o por Wiesler.",
   "Hempf usa informa\xc3\xa7\xc3\xa3o sobre a depend\xc3\xaancia qu\xc3\xadmica de Christa-Maria para for\xc3\xa7\xc3\xa1-la a revelar a autoria do artigo. A refer\xc3\xaancia ajuda a compreender a prote\xc3\xa7\xc3\xa3o da intimidade e da vida privada. N\xc3\xa3o demonstra, por si, viola\xc3\xa7\xc3\xa3o da honra ou da imagem nem indeniza\xc3\xa7\xc3\xa3o por dano material ou moral.\x0a""A Stasi instala escutas no apartamento do dramaturgo, monitoradas a partir do s\xc3\xb3t\xc3\xa3o por Wiesler. A refer\xc3\xaancia ajuda a compreender a prote\xc3\xa7\xc3\xa3o da intimidade e da vida privada. N\xc3\xa3o demonstra, por si, viola\xc3\xa7\xc3\xa3o da honra ou da imagem nem indeniza\xc3\xa7\xc3\xa3o por dano material ou moral.",
   "a prote\xc3\xa7\xc3\xa3o da intimidade e da vida privada", "Ilustra\xc3\xa7\xc3\xa3o de viola\xc3\xa7\xc3\xa3o", "REF-FIL-0003"},
  {"CF88:ART.5:INC.X|REF-LIV-0001", "1984", "LIVRO", 1949, 91,
   "A teletela recebe e transmite; capta os sons e observa Winston dentro de casa.",
   "A teletela recebe e transmite; capta os sons e observa Winston dentro de casa. A refer\xc3\xaancia ajuda a compreender a prote\xc3\xa7\xc3\xa3o da intimidade e da vida privada. N\xc3\xa3o demonstra, por si, viola\xc3\xa7\xc3\xa3o da honra ou da imagem nem indeniza\xc3\xa7\xc3\xa3o por dano material ou moral.",
   "a prote\xc3\xa7\xc3\xa3o da intimidade e da vida privada", "Ilustra\xc3\xa7\xc3\xa3o de viola\xc3\xa7\xc3\xa3o", "REF-LIV-0001"},
  {"CF88:ART.62:CAPUT|EXP-JOG-002", "Suzerain", "JOGO", 2020, 74,
   "RPG pol\xc3\xadtico em que o presidente de uma rep\xc3\xba""blica em transi\xc3\xa7\xc3\xa3o decide reformas constitucionais, or\xc3\xa7""amento e rela\xc3\xa7\xc3\xb5""es federativas.",
   "Suzerain coloca o jogador na posi\xc3\xa7\xc3\xa3o de Presidente e permite o uso de atos executivos e decretos dentro de um sistema de freios institucionais. A experi\xc3\xaancia ajuda a visualizar a tens\xc3\xa3o entre rapidez decis\xc3\xb3ria do Executivo e controle pelos demais Poderes, que tamb\xc3\xa9m est\xc3\xa1 presente no regime constitucional das medidas provis\xc3\xb3rias.",
   "Serve como analogia institucional. O sistema do jogo n\xc3\xa3o reproduz o regime brasileiro das medidas provis\xc3\xb3rias, seus prazos, limita\xc3\xa7\xc3\xb5""es materiais, trancamento de pauta ou processo de convers\xc3\xa3o em lei.\x0aLimites: Sistema pol\xc3\xadtico fict\xc3\xad""cio; conex\xc3\xa3o anal\xc3\xb3gica (a\xc3\xa7\xc3\xa3o normativa urgente do Executivo x controle institucional), n\xc3\xa3o um regime de medida provis\xc3\xb3ria.", "", "EXP-JOG-002 \xc2\xb7 REFERENCE_EXPANSION_01"},
  {"CF88:ART.6:CAPUT|EXP-FIL-006", "Eu, Daniel Blake", "FILME", 2016, 73,
   "Katie, m\xc3\xa3""e de duas crian\xc3\xa7""as, e Daniel enfrentam falta de sustento e recorrem a banco alimentar.",
   "Katie, m\xc3\xa3""e de duas crian\xc3\xa7""as, e Daniel enfrentam falta de sustento e recorrem a banco alimentar. A refer\xc3\xaancia ajuda a compreender o direito social \xc3\xa0 alimenta\xc3\xa7\xc3\xa3o. N\xc3\xa3o demonstra os demais direitos sociais enumerados no art. 6\xc2\xba.",
   "o direito social \xc3\xa0 alimenta\xc3\xa7\xc3\xa3o", "Ilustra\xc3\xa7\xc3\xa3o de consequ\xc3\xaancia", "EXP-FIL-006"},
  {"CF88:ART.6:CAPUT|EXP-LIV-008", "A Cor da Lei", "LIVRO", 2017, 75,
   "Rothstein analisa como pol\xc3\xadticas federais, estaduais e locais produziram segrega\xc3\xa7\xc3\xa3o residencial.",
   "Rothstein analisa como pol\xc3\xadticas federais, estaduais e locais produziram segrega\xc3\xa7\xc3\xa3o residencial. A refer\xc3\xaancia ajuda a compreender o direito social \xc3\xa0 moradia. N\xc3\xa3o demonstra os demais direitos sociais enumerados no art. 6\xc2\xba.",
   "o direito social \xc3\xa0 moradia", "Ilustra\xc3\xa7\xc3\xa3o de consequ\xc3\xaancia", "EXP-LIV-008"},
  {"CF88:ART.6:CAPUT|REF-DOC-0004", "Ilha das Flores", "DOCUMENT\xc3\x81RIO", 1989, 73,
   "Mulheres e crian\xc3\xa7""as sem recursos recolhem, em tempo limitado, os restos de alimento rejeitados para os porcos.",
   "Mulheres e crian\xc3\xa7""as sem recursos recolhem, em tempo limitado, os restos de alimento rejeitados para os porcos. A refer\xc3\xaancia ajuda a compreender o direito social \xc3\xa0 alimenta\xc3\xa7\xc3\xa3o. N\xc3\xa3o demonstra os demais direitos sociais enumerados no art. 6\xc2\xba.",
   "o direito social \xc3\xa0 alimenta\xc3\xa7\xc3\xa3o", "Ilustra\xc3\xa7\xc3\xa3o de consequ\xc3\xaancia", "REF-DOC-0004"},
  {"CF88:ART.6:CAPUT|REF-FIL-0004", "Filad\xc3\xa9lfia", "FILME", 1993, 76,
   "Advogados movem a\xc3\xa7\xc3\xa3o contra escrit\xc3\xb3rio por discrimina\xc3\xa7\xc3\xa3o ligada \xc3\xa0 AIDS no ambiente de trabalho.",
   "Advogados movem a\xc3\xa7\xc3\xa3o contra escrit\xc3\xb3rio por discrimina\xc3\xa7\xc3\xa3o ligada \xc3\xa0 AIDS no ambiente de trabalho. A refer\xc3\xaancia ajuda a compreender o direito social ao trabalho. N\xc3\xa3o demonstra os demais direitos sociais enumerados no art. 6\xc2\xba.",
   "o direito social ao trabalho", "Ilustra\xc3\xa7\xc3\xa3o de consequ\xc3\xaancia", "REF-FIL-0004"},
  {"CF88:ART.6:CAPUT|REF-LIV-0004", "Quarto de Despejo", "LIVRO", 1960, 87,
   "O di\xc3\xa1rio descreve a fome vivida por Carolina e seus filhos na favela do Canind\xc3\xa9.\x0a""A experi\xc3\xaancia narrada ocorre em moradia prec\xc3\xa1ria no Canind\xc3\xa9, com car\xc3\xaancias materiais da fam\xc3\xadlia.",
   "O di\xc3\xa1rio descreve a fome vivida por Carolina e seus filhos na favela do Canind\xc3\xa9. A refer\xc3\xaancia ajuda a compreender o direito social \xc3\xa0 alimenta\xc3\xa7\xc3\xa3o. N\xc3\xa3o demonstra os demais direitos sociais enumerados no art. 6\xc2\xba.\x0a""A experi\xc3\xaancia narrada ocorre em moradia prec\xc3\xa1ria no Canind\xc3\xa9, com car\xc3\xaancias materiais da fam\xc3\xadlia. A refer\xc3\xaancia ajuda a compreender o direito social \xc3\xa0 moradia. N\xc3\xa3o demonstra os demais direitos sociais enumerados no art. 6\xc2\xba.",
   "o direito social \xc3\xa0 alimenta\xc3\xa7\xc3\xa3o; o direito social \xc3\xa0 moradia", "Ilustra\xc3\xa7\xc3\xa3o de consequ\xc3\xaancia", "REF-LIV-0004"},
  {"CF88:ART.6:CAPUT|REF-LIV-0007", "Ensaio sobre a Cegueira", "LIVRO", 1995, -1,
   "No manic\xc3\xb4mio, um grupo de internos domina os demais e toma as ra\xc3\xa7\xc3\xb5""es de comida, privando-os do acesso livre \xc3\xa0 alimenta\xc3\xa7\xc3\xa3o.",
   "No manic\xc3\xb4mio, um grupo de internos domina os demais e toma as ra\xc3\xa7\xc3\xb5""es de comida, privando-os do acesso livre \xc3\xa0 alimenta\xc3\xa7\xc3\xa3o. A refer\xc3\xaancia ajuda a compreender o direito social \xc3\xa0 alimenta\xc3\xa7\xc3\xa3o. N\xc3\xa3o demonstra os demais direitos sociais enumerados no art. 6\xc2\xba.",
   "o direito social \xc3\xa0 alimenta\xc3\xa7\xc3\xa3o", "Ilustra\xc3\xa7\xc3\xa3o de consequ\xc3\xaancia", "REF-LIV-0007"},
  {"CF88:ART.7:INC.IV|EXP-LIV-004", "Cidadania no Brasil: O Longo Caminho", "LIVRO", 2001, 59,
   "Carvalho registra a previs\xc3\xa3o do sal\xc3\xa1rio m\xc3\xadnimo na Constitui\xc3\xa7\xc3\xa3o de 1934 e sua ado\xc3\xa7\xc3\xa3o em 1940.",
   "Carvalho registra a previs\xc3\xa3o do sal\xc3\xa1rio m\xc3\xadnimo na Constitui\xc3\xa7\xc3\xa3o de 1934 e sua ado\xc3\xa7\xc3\xa3o em 1940. A refer\xc3\xaancia ajuda a compreender a forma\xc3\xa7\xc3\xa3o hist\xc3\xb3rica do direito ao sal\xc3\xa1rio m\xc3\xadnimo. N\xc3\xa3o demonstra o atendimento de todas as necessidades enumeradas, os crit\xc3\xa9rios atuais de reajuste ou a veda\xc3\xa7\xc3\xa3o de vincula\xc3\xa7\xc3\xa3o.",
   "a forma\xc3\xa7\xc3\xa3o hist\xc3\xb3rica do direito ao sal\xc3\xa1rio m\xc3\xadnimo", "Contextualiza\xc3\xa7\xc3\xa3o hist\xc3\xb3rica", "EXP-LIV-004"},
  {"CF88:ART.7:INC.XXXIII|EXP-JOG-003", "Frostpunk", "JOGO", 2018, 78,
   "Simula\xc3\xa7\xc3\xa3o de sobreviv\xc3\xaancia em que o jogador administra recursos, infraestrutura e leis da \xc3\xbaltima cidade em ambiente glacial.",
   "Em uma cidade em crise, o jogador pode aprovar uma lei que coloca crian\xc3\xa7""as para trabalhar e sente as consequ\xc3\xaancias da escolha.",
   "Ajuda a problematizar por que a Constitui\xc3\xa7\xc3\xa3o pro\xc3\xad""be o trabalho infantil, mesmo em situa\xc3\xa7\xc3\xb5""es de crise. Mundo fict\xc3\xad""cio; n\xc3\xa3o demonstra o contrato de aprendizagem.\x0aLimites: Mundo fict\xc3\xad""cio. A mec\xc3\xa2nica ajuda a problematizar o trabalho infantil, mas n\xc3\xa3o reproduz as idades, exce\xc3\xa7\xc3\xb5""es e o contrato de aprendizagem previstos no direito brasileiro.", "", "EXP-JOG-003 \xc2\xb7 REFERENCE_EXPANSION_01"},
  {"CF88:ART.86:CAPUT|EXP-DOC-006", "Excelent\xc3\xadssimos", "DOCUMENT\xc3\x81RIO", 2018, 76,
   "Document\xc3\xa1rio de observa\xc3\xa7\xc3\xa3o sobre a C\xc3\xa2mara dos Deputados durante a crise pol\xc3\xadtica e o impeachment de 2016.",
   "O document\xc3\xa1rio acompanha a C\xc3\xa2mara dos Deputados durante o processo de impeachment de 2015\xe2\x80\x93""2016, mostrando vota\xc3\xa7\xc3\xa3o, articula\xc3\xa7\xc3\xa3o e discursos.",
   "Ajuda a visualizar a etapa de admiss\xc3\xa3o na C\xc3\xa2mara. N\xc3\xa3o explica o julgamento pelo Senado em detalhe nem o regime dos crimes comuns.\x0aLimites: Evento politicamente sens\xc3\xadvel; a ficha deve tratar s\xc3\xb3 do procedimento constitucional.", "", "EXP-DOC-006 \xc2\xb7 REFERENCE_EXPANSION_01"},
};
